import type { SeoFixInput, SeoFixProposal } from "./types.js";

/** Truncates on a word boundary and marks the cut, so a templated tag value never silently exceeds its own field's practical length. */
function truncate(text: string, maxLength: number): string {
  const trimmed = text.trim();
  if (trimmed.length <= maxLength) return trimmed;
  const cut = trimmed.slice(0, maxLength - 1);
  const lastSpace = cut.lastIndexOf(" ");
  return `${(lastSpace > maxLength * 0.6 ? cut.slice(0, lastSpace) : cut).trimEnd()}…`;
}

/** A conservative, always-valid slug for use inside a generated file/URL fragment — never derived from unescaped free text. */
function slugify(text: string): string {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-+|-+$)/g, "");
  return slug.length > 0 ? slug : "fix";
}

function buildSitemapStub(rec: SeoFixInput): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    "  <!--",
    `    Generated by karos-seo-fix for ${rec.recId} — a STARTER sitemap shape, not a crawl.`,
    "    This actuator has no site-fetch (SCRUM-261 scope guard): populate <url> entries",
    "    from a real crawl before this file is ever proposed to a client.",
    "  -->",
    "</urlset>",
    "",
  ].join("\n");
}

function buildJsonLdStub(rec: SeoFixInput): Record<string, unknown> {
  return {
    "@context": "https://schema.org",
    "@type": "Thing",
    "@id": `#seo-fix-${slugify(rec.recId)}`,
    "seoFix:recId": rec.recId,
    "seoFix:draftReason": rec.recommendation,
    "seoFix:note": "Placeholder JSON-LD shape — the real @type and properties are a human judgment call (which fields this record's check actually supports), made when this draft is reviewed, not invented here.",
  };
}

function buildGuidedKitDocument(rec: SeoFixInput): string {
  // RFC-09 §7's "guided-kit" artifact, in miniature: the client-facing recommendation, the
  // internal evidence a developer needs, and an explicit statement of what Karos did and did
  // not do — matching `fix-recipes.md`'s "Honest scope" language the RFC cites verbatim.
  return [
    `# ${rec.recId} — guided fix kit`,
    "",
    "## What we found",
    rec.recommendation,
    "",
    "## The evidence behind it",
    rec.check.length > 0 ? rec.check : "(no evidence string recorded on this catalog entry)",
    "",
    "## What Karos did and did not do",
    "We identified this and drafted this kit. We do not write this fix to your site directly — " +
      "either because it needs a human decision this actuator must not make on your behalf, or " +
      "because it needs an account connection or credential this actuator does not hold.",
  ].join("\n");
}

/**
 * One content generator per `FixAction`, keyed generically — see `dispatch.ts`'s module doc for
 * why this is a `Record` keyed on the union rather than a `switch`/`if` chain, and why that is the
 * mechanism that makes "zero `if`s on a specific `recId`" true by construction rather than by
 * discipline.
 */
export const PROPOSAL_BUILDERS: { [K in SeoFixProposal["fixAction"]]: (rec: SeoFixInput) => Extract<SeoFixProposal, { fixAction: K }> } = {
  meta_title: (rec) => ({ fixAction: "meta_title", tag: "title", proposedValue: truncate(rec.recommendation, 60) }),
  meta_description: (rec) => ({ fixAction: "meta_description", tag: 'meta[name="description"]', proposedValue: truncate(rec.recommendation, 155) }),
  og_image: (rec) => ({ fixAction: "og_image", tag: 'meta[property="og:image"]', proposedValue: truncate(rec.recommendation, 200) }),
  canonical: (rec) => ({ fixAction: "canonical", tag: 'link[rel="canonical"]', proposedValue: truncate(rec.recommendation, 200) }),
  image_alt: (rec) => ({ fixAction: "image_alt", tag: "img[alt]", proposedValue: truncate(rec.recommendation, 125) }),
  sitemap: (rec) => ({ fixAction: "sitemap", fileName: "sitemap.xml", mimeType: "application/xml", content: buildSitemapStub(rec) }),
  schema: (rec) => ({ fixAction: "schema", mimeType: "application/ld+json", jsonLd: buildJsonLdStub(rec) }),
  indexing: (rec) => ({ fixAction: "indexing", file: "robots.txt", directive: truncate(rec.recommendation, 300) }),
  manual: (rec) => ({ fixAction: "manual", kit: "guided-kit", document: buildGuidedKitDocument(rec) }),
};
