import { z } from "zod";

/**
 * The four non-negotiable draft constraints (RFC-08 task spec /
 * `references/response-craft.md`'s anti-patterns): no conceding fault for
 * an incident we cannot verify, no blaming the reviewer, no public
 * financial promise (refunds/compensation/credits are a doctrine violation
 * and on some platforms a policy violation), and no fact outside what
 * `01-facts.md` actually states.
 */
export const DOCTRINE_CONSTRAINTS = ["no_fault_concession", "no_blame", "no_financial_promises", "facts_grounded"] as const;
export type DoctrineConstraint = (typeof DOCTRINE_CONSTRAINTS)[number];

export const DoctrineVerdictSchema = z.object({
  constraint: z.enum(DOCTRINE_CONSTRAINTS),
  verdict: z.enum(["pass", "fail"]),
  /** The exact substring of the draft that justifies the verdict — empty only when the constraint cleanly passes with nothing to quote. */
  quote: z.string(),
  rationale: z.string().min(1),
});
export type DoctrineVerdict = z.infer<typeof DoctrineVerdictSchema>;

/**
 * Explains exactly how a verdict set failed to cover the four constraints.
 * Returns `null` when the set is well-formed.
 *
 * Cardinality alone (`.length(4)`) is NOT enough, and the gap is not
 * theoretical: `doctrine-gate.ts` runs its mechanical backstop per SUPPLIED
 * verdict, so a model that returned four verdicts all naming
 * `no_fault_concession` would skip the `no_financial_promises`,
 * `no_blame` and `facts_grounded` bright-line scans entirely — and
 * `overallPass` could then come back `true` for a draft promising a refund.
 * The whole point of this tool is that arithmetic backstops judgment; a
 * malformed verdict set silently disables the arithmetic.
 */
export function describeVerdictSetViolation(verdicts: readonly { constraint: DoctrineConstraint }[]): string | null {
  const seen = new Set<DoctrineConstraint>();
  const duplicated = new Set<DoctrineConstraint>();
  for (const v of verdicts) {
    if (seen.has(v.constraint)) duplicated.add(v.constraint);
    seen.add(v.constraint);
  }
  const missing = DOCTRINE_CONSTRAINTS.filter((c) => !seen.has(c));
  if (missing.length === 0 && duplicated.size === 0 && verdicts.length === DOCTRINE_CONSTRAINTS.length) {
    return null;
  }
  const parts: string[] = [];
  if (missing.length > 0) parts.push(`missing a verdict for: ${missing.join(", ")}`);
  if (duplicated.size > 0) parts.push(`duplicate verdicts for: ${[...duplicated].join(", ")}`);
  if (parts.length === 0) parts.push(`expected exactly ${DOCTRINE_CONSTRAINTS.length} verdicts, got ${verdicts.length}`);
  return `the doctrine verdict set must cover each of the ${DOCTRINE_CONSTRAINTS.length} constraints exactly once (${DOCTRINE_CONSTRAINTS.join(", ")}) — ${parts.join("; ")}`;
}

export const DoctrineGateInputSchema = z.object({
  draftText: z.string().min(1),
  /** Lines from the client's `01-facts.md` — the closed universe `facts_grounded` claims must trace to. */
  factsBase: z.array(z.string()).default([]),
  /**
   * The four quoted verdicts from the SEPARATE model pass (RFC-08 step 09 —
   * "the model that wrote a sentence is the worst judge of whether it
   * conceded fault", so this is never generated by the same turn that
   * drafted the reply). This tool's own job is mechanical: validate the
   * shape, compute the overall gate decision, and run independent
   * backstop checks that can override a model "pass" it disagrees with.
   *
   * The refinement below is load-bearing, not defensive tidiness — see
   * `describeVerdictSetViolation`.
   */
  modelVerdicts: z
    .array(DoctrineVerdictSchema)
    .length(DOCTRINE_CONSTRAINTS.length)
    .superRefine((verdicts, ctx) => {
      const violation = describeVerdictSetViolation(verdicts);
      if (violation !== null) {
        ctx.addIssue({ code: "custom", message: violation });
      }
    }),
});
export type DoctrineGateInput = z.infer<typeof DoctrineGateInputSchema>;

/**
 * Thrown by `evaluateDoctrineGate` when the model's verdict set does not
 * cover the four constraints exactly once. Deliberately an exception rather
 * than a quiet `overallPass: false`: a malformed verdict set means the gate
 * did not actually run, which is a tooling/validation fault for a human to
 * fix — never a content verdict about the draft, and never a silent pass
 * (RFC-01 §6's "never recorded as a content verdict").
 */
export class DoctrineVerdictSetError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "DoctrineVerdictSetError";
  }
}

export interface MechanicalOverride {
  constraint: DoctrineConstraint;
  reason: string;
}

export interface DoctrineGateResult {
  overallPass: boolean;
  verdicts: DoctrineVerdict[];
  /** Any backstop check that forced a constraint to `fail` despite the model's own verdict saying `pass` — surfaced separately so a human reviewer can see where the mechanical layer disagreed with the judgment pass. */
  mechanicalOverrides: MechanicalOverride[];
  /** `publish.py`'s own `guard_text` rule, checked here too so it is caught at the gate, not only at the publish rail. */
  unfilledTemplateDetected: boolean;
}
