// Verbatim port of the legacy karos-agents lab-spec config (RFC-04 "port the scoring config as-is").
// Source: karos-agents/products/onboarding/step-02-seo-geo/config/seo-geo-rec-catalog.json
// DO NOT hand-edit values here — this is a byte-for-fidelity transcription of the JSON asset.
export const recCatalogData = {
 "SEO-01": {
  "id": "SEO-01",
  "recommendation": "Deterministic 0-100 SEO score",
  "check": "Weighted sum of the eligibility/technical/on-page/structure checks above; each input a fixed threshold; same frozen crawl → same score.",
  "impact": "critical",
  "effort": "heavy",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "PLATFORM-GUIDANCE rows 1-13; RESEARCH-FINDINGS §2; Google CWV thresholds [PRIMARY]",
  "lever": "SEO"
 },
 "BOTH-06": {
  "id": "BOTH-06",
  "recommendation": "Eliminate cannibalization & thin pages",
  "check": "No two indexable pages share >70% title/H1 + primary-query overlap (cannibalization flag); no indexable page <300 words without justification (thin flag): pass/fail.",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 [PRIMARY]; Helpful Content folded into core 2024-03-05",
  "lever": "BOTH"
 },
 "SEO-02": {
  "id": "SEO-02",
  "recommendation": "Title length, truncation & rewrite-mismatch guard",
  "check": "char count ≤60 (hard gate) AND rendered width ≤600px using a **pinned font-metrics table** AND duplicate `<title>` == 0 across crawl AND exactly one H1 AND token overlap `<title>`↔H1 ≥50% (pass/fail per page).",
  "impact": "high",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google \"How to write good titles\" + title-link docs; totheweb/Zyppy pixel-width 2026",
  "lever": "SEO"
 },
 "GEO-30": {
  "id": "GEO-30",
  "recommendation": "Branded search demand",
  "check": "Branded-query impressions in GSC trending up ≥20% QoQ (number, once GSC verified); pre-GSC, branded search-volume estimate up vs baseline. **Measurement = a3/i2 + GSC; drivers = ads/content.**",
  "impact": "medium",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization + i2 Performance Reporting (measure); a1 TikTok/Meta + a2 Google Ads (drive)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Ahrefs 75k-brand study 2025-12-12 (brand search r=0.334) [VENDOR-correlational]; GSC verification pending",
  "lever": "GEO"
 },
 "SEO-03": {
  "id": "SEO-03",
  "recommendation": "Verify/monitor Knowledge Panel & brand SERP",
  "check": "Knowledge Panel DOM block (kp-blk/knowledge-panel) renders for exact brand-name query → pass/fail, re-checkable per run.",
  "impact": "medium",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (rank-tracker / geo-report)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "stackmatix Organization Schema Guide 2026; Google Organization structured-data docs 2026",
  "lever": "SEO"
 },
 "SEO-04": {
  "id": "SEO-04",
  "recommendation": "Core Web Vitals pass at 75th percentile",
  "check": "At p75: LCP≤2.5s, INP≤200ms, CLS≤0.1 (pass/fail each); all three pass = \"good.\"",
  "impact": "medium",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (lighthouse-audit)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google CWV thresholds 2026 (web.dev) [PRIMARY]; CWV = hygiene/tiebreaker",
  "lever": "SEO",
  "data_source_ladder": "field (CrUX/GSC p75, requires connected Google) > lab (FREE local unlighthouse pass via claude-seo v2.2.0 extensions/unlighthouse, no key; label 'MEASURED (lab)', distinct from field p75) > NEED-DATA (excluded from grade, never guessed). v1.1: the lab tier means SEO-04 no longer defaults to NEED-DATA when Google is unconnected."
 },
 "BOTH-19": {
  "id": "BOTH-19",
  "recommendation": "Mobile-friendly / responsive with content parity",
  "check": "Meta viewport present (bool); **DOM text-node diff ratio ≥0.95 between 360px and desktop renders using a pinned headless-browser version** (replaces \"content parity\" judgement); no horizontal scroll at 360px (bool).",
  "impact": "medium",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (technical-seo-checker, lighthouse-audit)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 [PRIMARY]; mobile-first indexing",
  "lever": "BOTH"
 },
 "BOTH-20": {
  "id": "BOTH-20",
  "recommendation": "HTTPS enforced site-wide with valid cert",
  "check": "All key URLs HTTPS + valid non-expired cert (bool); HTTP→HTTPS 301 (bool); mixed-content warnings == 0 on key templates.",
  "impact": "medium",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (technical-seo-checker)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google page-experience guidance 2026-06-15 [PRIMARY]",
  "lever": "BOTH"
 },
 "SEO-05": {
  "id": "SEO-05",
  "recommendation": "Crawl-budget hygiene",
  "check": "Soft-404 count == 0; redirect chains >1 hop == 0; parameterized URL variants per template ≤ defined cap. Reproducible from a crawl export.",
  "impact": "medium",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (technical-seo-checker, geo-technical)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google \"reduce duplicate content / crawling best practices\" 2026-06-15 [PRIMARY]",
  "lever": "SEO"
 },
 "SEO-06": {
  "id": "SEO-06",
  "recommendation": "Meta description presence/length/uniqueness",
  "check": "Present (bool) AND 120 ≤ char count ≤ 158 AND duplicate-description count == 0 across crawl (pass/fail per page).",
  "impact": "medium",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google \"How to write meta descriptions\" 2026; WebCitz/Analytify 2026",
  "lever": "SEO"
 },
 "BOTH-15": {
  "id": "BOTH-15",
  "recommendation": "Backlink quality: editorial-link ratio",
  "check": "Share of referring domains classified editorial **(link in `<main>`/`<article>`, not `<nav>`/`<footer>`, anchor domain not in a pinned known-directory list)** ≥70%, computed against a **pinned backlink-export date + tool version** (BOTH-18).",
  "impact": "medium",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (backlink-analyzer / domain-authority-auditor)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "colabdxb backlink study 2026 (92.2% editorial) [VENDOR]; Illyes 2023-09-25 (links not top-3)",
  "lever": "BOTH"
 },
 "BOTH-21": {
  "id": "BOTH-21",
  "recommendation": "Keyword/intent targeting without stuffing",
  "check": "Primary-keyword density ≤2.5% AND no exact phrase repeated >5× per page AND one declared primary intent per URL (no two URLs share the same primary query) (pass/fail).",
  "impact": "medium",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Princeton GEO KDD 2024 (stuffing -8%) [CONTROLLED]; Google 2026-06-15 [PRIMARY]",
  "lever": "BOTH"
 },
 "SEO-07": {
  "id": "SEO-07",
  "recommendation": "Clean, descriptive, stable URLs",
  "check": "Path depth ≤4 segments AND no spaces/uppercase/underscores AND query-param count == 0 on indexable content URLs (pass/fail per URL).",
  "impact": "medium",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google URL-structure best practices 2026; PLATFORM-GUIDANCE rule 6",
  "lever": "SEO"
 },
 "SEO-08": {
  "id": "SEO-08",
  "recommendation": "Image alt text & filename optimization",
  "check": "Share of content images with non-empty descriptive alt ≥95% (pass/fail); 0 alt attrs that are just filename or keyword-stuffed.",
  "impact": "medium",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google image SEO best practices 2026",
  "lever": "SEO"
 },
 "SEO-09": {
  "id": "SEO-09",
  "recommendation": "Referring-domain velocity sanity-check",
  "check": "New referring domains/month ≤ age-scaled ceiling (site <6mo: ≤6; 6-12mo: ≤12; DR≥50 established: no cap unless >50/mo spike with no PR event) (pass/fail), against a pinned backlink-export date.",
  "impact": "medium",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (backlink-analyzer + alert-manager)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "linkbuildingjournal link-velocity 2026; 2024 Google API leak (hostAge) [LEAK]",
  "lever": "SEO"
 },
 "SEO-10": {
  "id": "SEO-10",
  "recommendation": "Toxic / negative-SEO backlink monitoring",
  "check": "No single-week influx >50 new referring domains from pinned spam-category tags (pass/fail), from backlink-tool category tags + date filter (pinned export).",
  "impact": "medium",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (backlink-analyzer + alert-manager)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "authority.builders/bluetree 2026; Google SpamBrain post-2022",
  "lever": "SEO"
 },
 "BOTH-17": {
  "id": "BOTH-17",
  "recommendation": "Classic-vs-AI divergence (top-10 overlap)",
  "check": "ai_organic_overlap = (#queries where brand is BOTH in organic top-10 AND cited in AI answer)/(#queries where brand is cited)×100. Reproducible over the **frozen query set + captured SERP/answer snapshot** (BOTH-18).",
  "impact": "medium",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (rank-tracker + geo-monitor join)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Moz AI Mode 40k-query study 2026-02 (88% of AI Mode citations NOT in organic top-10) [VENDOR]",
  "lever": "BOTH"
 },
 "BOTH-01": {
  "id": "BOTH-01",
  "recommendation": "Pages indexed & snippet-eligible",
  "check": "Per URL: HTTP 200 AND no `noindex` in meta robots/X-Robots-Tag AND no page-level `nosnippet`/`max-snippet:0` (pass/fail per URL; report % of key URLs passing).",
  "impact": "critical",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google \"Optimizing your website for generative AI features,\" Search Central, 2026-06-15 [PRIMARY]",
  "lever": "BOTH"
 },
 "BOTH-02": {
  "id": "BOTH-02",
  "recommendation": "Publicly accessible & crawlable (no login/paywall)",
  "check": "Anonymous fetch: primary content in crawlable HTML without auth (pass/fail per URL); robots.txt does not Disallow the path for Googlebot (bool).",
  "impact": "critical",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 [PRIMARY]",
  "lever": "BOTH"
 },
 "GEO-01": {
  "id": "GEO-01",
  "recommendation": "Cross-engine AI crawler access",
  "check": "robots.txt: none of {OAI-SearchBot, PerplexityBot, ClaudeBot, Googlebot, Bingbot} Disallowed for entity/key paths (5 bools, all pass) AND GSC Generative-AI opt-out toggle == OFF (where GSC verified) AND emit a training-vs-citation table per crawler. **Caveat: ChatGPT-User no longer honors robots.txt (Dec 2025) — only the OAI-SearchBot Disallow leg is load-bearing for ChatGPT.** GSC leg blocked on GSC_SERVICE_ACCOUNT_KEY/GSC_SITE_URL.",
  "impact": "critical",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "OpenAI Crawlers Overview 2026; Google generative-AI guide 2026-06-15 + GSC AI opt-out toggle ~mid-June 2026 [PRIMARY]; ChatGPT-User robots.txt non-compliance Dec 2025",
  "lever": "GEO"
 },
 "GEO-02": {
  "id": "GEO-02",
  "recommendation": "Front-load a self-contained answer capsule",
  "check": "Opening block under H1 (and each target H2) is 40-60 words AND begins within first 30% of body word-count; containing section 134-167 words (pass/fail per section); capsule on ≥90% of target H2s (count/total).",
  "impact": "critical",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Univ. Tokyo+Tsukuba structural-GEO study Mar 2026 (~44% citations from first third); Princeton GEO KDD 2024 [CONTROLLED]; PLATFORM-GUIDANCE §3 rule 12",
  "lever": "GEO"
 },
 "GEO-03": {
  "id": "GEO-03",
  "recommendation": "Embed Princeton evidence levers (stats, quotes, cited sources)",
  "check": "Each major section ≥1 numeric statistic (regex digits+unit/%) AND ≥1 cited source link **to a domain on a pinned allowlist (DR≥X via a pinned backlink dataset, or an explicit gazetteer)**; page-level ≥1 attributed quotation AND ≥3 outbound citations to allowlist domains (counts, pass/fail).",
  "impact": "critical",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Princeton \"GEO\" Aggarwal et al., arXiv 2311.09735, KDD 2024 **[CONTROLLED]**: statistics +31%, quotations +41%, cite-sources +30%; Anthropic Claude citations guidance [PRIMARY]",
  "lever": "GEO"
 },
 "BOTH-03": {
  "id": "BOTH-03",
  "recommendation": "Unique, non-commodity content with a POV",
  "check": "5-shingle Jaccard similarity vs a **versioned, hashed snapshot of the top-10 captured at config time** ≤0.40 (pass/fail). Re-pull only on a logged version bump (BOTH-18).",
  "impact": "critical",
  "effort": "heavy",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 [PRIMARY] (\"unique, compelling, and useful… more than any other suggestion\")",
  "lever": "BOTH"
 },
 "GEO-08": {
  "id": "GEO-08",
  "recommendation": "ChatGPT: allow OAI-SearchBot + rank in Bing",
  "check": "robots.txt does not Disallow OAI-SearchBot for the audited path (bool — the enforceable leg) AND `site:` query in Bing returns the page / present in BWT URL inspection (bool). **ChatGPT-User Disallow no longer enforceable (Dec 2025); do not treat it as load-bearing.**",
  "impact": "critical",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "OpenAI Publishers FAQ / ChatGPT Search docs 2026 [PRIMARY]; Seer Interactive 500-citation (~87% Bing-overlap) 2026; ChatGPT-User robots.txt non-compliance Dec 2025",
  "lever": "GEO"
 },
 "GEO-10": {
  "id": "GEO-10",
  "recommendation": "Confirm AI/search crawler access for entity pages",
  "check": "OAI-SearchBot, PerplexityBot, ClaudeBot, Googlebot each NOT Disallowed for entity/about pages in robots.txt → 4 bools, all pass.",
  "impact": "critical",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 [PRIMARY]; OpenAI Publishers FAQ",
  "lever": "GEO"
 },
 "GEO-09": {
  "id": "GEO-09",
  "recommendation": "Densify evidence per-engine (Claude/Perplexity)",
  "check": "**Citation density = inline-citation count / 100 words ≥ 0.8** (replaces undefinable \"factual-claims ratio\") AND named author byline present AND ≥1 original statistic/dataset (counts/bools, pass/fail).",
  "impact": "critical",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Anthropic Claude citations guidance [PRIMARY]; Princeton GEO KDD 2024 [CONTROLLED]",
  "lever": "GEO"
 },
 "GEO-11": {
  "id": "GEO-11",
  "recommendation": "Citation share across the 5 engines (fixed-prompt panel)",
  "check": "citation_share_engine = (#prompts where brand domain is cited)/N over a **frozen captured response set (response_set_hash)** for N≈300 fixed prompts × 5 engines; blended = mean across engines. **Deterministic over the captured snapshot, not over live engines** (live runs mint a new hash). Flag when blended < category-leader share.",
  "impact": "critical",
  "effort": "medium",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard (extend geo-monitor: geo-report + performance-reporter)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "AuthorityTech \"AI Share of Voice\" 2026 + Averi \"Share of AI Voice\" 2026; engines locked per findings §1c [measurement-spine definition; critical as the metric the engagement keys off, not a vendor ranking claim]",
  "lever": "GEO"
 },
 "GEO-12": {
  "id": "GEO-12",
  "recommendation": "Deterministic 0-100 GEO score",
  "check": "Weighted sum of the GEO scoring inputs above; every input a fixed threshold/count read from a frozen snapshot; reproducible per BOTH-18.",
  "impact": "critical",
  "effort": "heavy",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard (geo-monitor: geo-citability, geo-crawlers, geo-brand-mentions, entity-optimizer)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Princeton GEO KDD 2024 [CONTROLLED]; repo task facts; Ahrefs 75k 2025-12-12 [VENDOR-correlational, used only as a weighting input for the off-site sub-score, not a causal ranking claim]; PLATFORM-GUIDANCE rows 3-15",
  "lever": "GEO"
 },
 "GEO-17": {
  "id": "GEO-17",
  "recommendation": "Single-H1 + question-style heading hierarchy",
  "check": "H1 count == 1 AND zero heading-level skips (pass/fail) AND share of H2/H3 phrased as questions OR matching a **frozen intent-string list** ≥50% on target pages.",
  "impact": "high",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google semantic-HTML guidance 2026-06-15 [PRIMARY]; AirOps question-heading study 2026; PLATFORM-GUIDANCE rule 6",
  "lever": "GEO"
 },
 "GEO-18": {
  "id": "GEO-18",
  "recommendation": "Recognized-entity density ≥15 / 1000 words w/ definitions",
  "check": "Recognized named entities/1000w ≥15, computed by a **version-pinned NER model id + KG/Wikidata gazetteer snapshot hash** AND ≥1 \"X is/are a…\" definitional sentence for the primary entity in first 30% (bool) AND anti-stuffing: no single non-stopword token >3% of body terms (pass/fail).",
  "impact": "high",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "AI Overview study 15,847 results / 63 industries (15+ entities = 4.8×, Wellows 2026) [VENDOR-correlational]; Frase 2026; Princeton GEO KDD 2024 (stuffing -8%) [CONTROLLED]",
  "lever": "GEO"
 },
 "BOTH-05": {
  "id": "BOTH-05",
  "recommendation": "Topic clusters w/ bidirectional pillar linking",
  "check": "Every cluster sub-page links to its pillar AND pillar links back (pass/fail per page); orphan count == 0; click-depth from home ≤3 for priority pages; generic anchors (\"click here\"/\"read more\") ≤5%; brand entity hub has ≥8 internal links to distinct entity pages with non-generic anchors.",
  "impact": "high",
  "effort": "heavy",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "ContentGrip/TopicalMap 2026 (bidirectional = 2.7× AI citations) [VENDOR]; Google site-architecture 2026",
  "lever": "BOTH"
 },
 "GEO-19": {
  "id": "GEO-19",
  "recommendation": "Add multimodal assets (image + video) to key pages",
  "check": "Priority pages with ≥1 original image OR embedded video OR data table alongside text (bool per page); site-wide share ≥90%; alt text on all content images (bool).",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (audit/flag) + e6 Motion / YouTube GEO Agent (net-new assets)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Wellows multimodal study Feb 2026 (~0.92 correlation) [VENDOR-correlational]; Google generative-AI guide 2026-06-15 (\"add high-quality images and video\") [PRIMARY]",
  "lever": "GEO"
 },
 "GEO-20": {
  "id": "GEO-20",
  "recommendation": "Freshness cadence with genuine dateModified ≤90d",
  "check": "dateModified within 90 days of crawl (bool, stretch 30) AND dateModified == sitemap lastmod == visible on-page date (consistency bool) AND body content changed since prior crawl (diff > threshold; blocks date-only edits).",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (freshness cadence) + e11 Newsletter / blog-writer (net-new)",
  "product_ref": {"id": "e14", "folder": "blog-agent", "status": "live"},
  "source": "AuthorityTech/Discovered Labs 2026 (content <30d cited ~3.2×) [VENDOR-correlational]; Perplexity recency skew",
  "lever": "GEO"
 },
 "GEO-21": {
  "id": "GEO-21",
  "recommendation": "Semantic completeness: full query fan-out on one page",
  "check": "Page covers ≥N of a **frozen, versioned static sub-intent checklist** (what/how/cost/vs/limitations) per topic (coverage = matched/checklist size, threshold e.g. ≥4/5). **Checklist is versioned, not live-fetched from PAA/autocomplete.**",
  "impact": "high",
  "effort": "heavy",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (content-gap-analysis + geo-content)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 (query fan-out + RAG) [PRIMARY]; \"IF-GEO\" arXiv 2601.13938 2026",
  "lever": "GEO"
 },
 "GEO-22": {
  "id": "GEO-22",
  "recommendation": "Q&A blocks in real query phrasing (prose, not FAQ schema)",
  "check": "Page has ≥3 question-form H2/H3 (ending in \"?\") each followed by a ≤80-word answer (count/pass-fail); answers present as crawlable HTML text, not only JSON-LD.",
  "impact": "high",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Machine Relations GEO-SFE 2026; caveat: Google removed FAQ rich results 2026-05-07 — value is on-page text, not markup",
  "lever": "GEO"
 },
 "BOTH-04": {
  "id": "BOTH-04",
  "recommendation": "Named, credentialed authors w/ bios + external sameAs",
  "check": "Page has a named author byline linked to an author page with ≥1 external sameAs profile (bool); anonymous pages flagged fail. Author Person JSON-LD emitted agent-direct.",
  "impact": "high",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Contently 2026-05-11 \"E-E-A-T and AI\"; leadgen-economy 2026 author-entity verification. *Directional note: a vendor study reported ~40% citation lift from visible credentials — `[VENDOR-directional]`, not used to justify the rank.*",
  "lever": "BOTH"
 },
 "GEO-14": {
  "id": "GEO-14",
  "recommendation": "Review-platform presence + sentiment",
  "check": "Avg star rating ≥4.3 across ≥3 vertical-relevant platforms (B2B: G2/Capterra; consumer: Trustpilot/Google/Yelp; BR: Reclame Aqui), each with ≥25 reviews (numbers, via platform APIs); FTC guard: zero gated/incentivized-without-disclosure reviews.",
  "impact": "high",
  "effort": "medium",
  "delivery": "advisory",
  "product": "**Review-Acquisition Program** (builds/solicits profiles) + r2 Online Reviews Monitoring (measures)",
  "product_ref": null,
  "source": "Feefo 2026 (ChatGPT references reviews 58%, Perplexity 100%; recommended avg 4.3★); FTC Fake Reviews Rule effective 2024-10-21",
  "lever": "GEO"
 },
 "GEO-15": {
  "id": "GEO-15",
  "recommendation": "Earn a Wikipedia article only when notability is met",
  "check": "Live non-stub English Wikipedia article at a stable title AND cites ≥3 independent reliable sources (count of distinct non-self references) → pass/fail. Treated as **entity-eligibility prerequisite**, not a citation lever.",
  "impact": "high",
  "effort": "heavy",
  "delivery": "advisory",
  "product": "a11 Wikipedia Page Creation (**catalog, not built**)",
  "product_ref": null,
  "source": "Profound/5WPR 680M-citation study 2026 (Wikipedia 47.9% of ChatGPT top-10 — *citation-source frequency, not proof your entry drives your citations*); page removed if notability not met",
  "lever": "GEO"
 },
 "GEO-16": {
  "id": "GEO-16",
  "recommendation": "Reddit presence in cited subreddits/threads",
  "check": "#Reddit threads ranking/cited for the **frozen target query set** where the brand or a disclosed brand expert has a substantive top-level comment/post ≥3 (number); astroturf guard: zero undisclosed-affiliation posts; 9:1 non-promotional ratio.",
  "impact": "high",
  "effort": "heavy",
  "delivery": "new-product",
  "product": "Reddit Presence Agent",
  "product_ref": {"id": "e15", "folder": "reddit-agent", "status": "building"},
  "source": "5WPR AI Citation Source Index 2026 (Reddit ~40.1%) [VENDOR-correlational]; Perplexity ~24-46.5% from Reddit 2026",
  "lever": "GEO"
 },
 "GEO-25": {
  "id": "GEO-25",
  "recommendation": "Wikipedia + Wikidata entity establishment",
  "check": "Live non-stub Wikipedia article (bool) AND Wikidata Q-item with ≥5 referenced statements (bool) → both pass. **Entity-eligibility prerequisite, not an asserted citation lever.**",
  "impact": "high",
  "effort": "heavy",
  "delivery": "advisory",
  "product": "a11 Wikipedia Page Creation (**catalog, not built**) + entity-optimizer",
  "product_ref": null,
  "source": "Discovered Labs/5WPR per-engine bias 2026 (ChatGPT ~47.9% Wikipedia — citation-source frequency); PLATFORM-GUIDANCE §2",
  "lever": "GEO"
 },
 "GEO-04": {
  "id": "GEO-04",
  "recommendation": "Unlinked brand-mention frequency across authoritative domains",
  "check": "Count of distinct authoritative referring domains **(DR≥40 via a pinned backlink dataset + export date)** that mention the exact brand name in body text in trailing 90 days ≥10 (number, reproducible per pinned snapshot); **authenticity guard: zero paid/sponsored placements (non-paid editorial only), FTC-disclosed.**",
  "impact": "high",
  "effort": "heavy",
  "delivery": "new-product",
  "product": "Digital-PR / Earned-Mention Agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Ahrefs 75,000-brand study 2025-12-12: unlinked mentions **r=0.664** vs backlinks r=0.218 — **strongest observed off-site correlate (correlational, vendor)**, not a proven cause; Kalicube 5,000-entity 2025",
  "lever": "GEO"
 },
 "GEO-06": {
  "id": "GEO-06",
  "recommendation": "Editorial earned-media placements on news/PR domains",
  "check": "#earned editorial placements (**non-paid, non-wire-only**) on DR≥60 news/trade domains (pinned dataset + export date) in trailing 90 days ≥3 (number); authenticity guard: paid/sponsored excluded.",
  "impact": "high",
  "effort": "heavy",
  "delivery": "advisory",
  "product": "Digital-PR / Earned-Mention Agent",
  "product_ref": null,
  "source": "Muck Rack >1M AI-citation analysis 2026 (82% earned, 94% non-paid) [VENDOR-correlational]; Fractl/Parse 2026",
  "lever": "GEO"
 },
 "GEO-05": {
  "id": "GEO-05",
  "recommendation": "YouTube: brand in titles + transcripts of query-matched videos",
  "check": "#owned/branded YouTube videos where brand name appears in BOTH title AND uploaded transcript/captions ≥5 for the target topic set (number, reproducible).",
  "impact": "high",
  "effort": "heavy",
  "delivery": "advisory",
  "product": "YouTube GEO Agent",
  "product_ref": null,
  "source": "Ahrefs 75k-brand study 2025-12-12: YouTube mentions **r=0.737 — strongest single observed correlate (correlational, vendor)**, not a tested lift; OtterlyAI YouTube Citation Study 2026",
  "lever": "GEO"
 },
 "GEO-13": {
  "id": "GEO-13",
  "recommendation": "Earned off-domain entity mentions on co-citation hubs",
  "check": "Branded web-mention count across a **fixed source set** over trailing 90 days ≥ baseline+X (count of distinct domains mentioning the exact brand name), reproducible per pinned snapshot.",
  "impact": "high",
  "effort": "heavy",
  "delivery": "new-product",
  "product": "Digital-PR / Earned-Mention Agent (+ i3 Social Listening / geo-brand-mentions measures)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Ahrefs 75k 2025-12-12 (branded mentions **r≈0.66**, correlational/vendor); findings (~80% of AI citations off own site, ~85% earned)",
  "lever": "GEO"
 },
 "BOTH-10": {
  "id": "BOTH-10",
  "recommendation": "Placement in third-party \"best of\" listicles & roundups",
  "check": "#distinct third-party \"best/top\" listicles or comparison pages (titles containing best|top|vs|comparison) ranking for the **frozen target query set** that name the brand ≥5 (number); avoid pay-for-placement.",
  "impact": "high",
  "effort": "medium",
  "delivery": "new-product",
  "product": "Comparison-Placement Program",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Discovered/linkbuildingjournal 2026 (43.8% of ChatGPT citations from blog-style listicles; \"best\" in title 3.24×) [VENDOR-correlational]",
  "lever": "BOTH"
 },
 "GEO-NEW-02": {
  "id": "GEO-NEW-02",
  "recommendation": "Owned comparison / \"[competitor] alternative\" / \"vs\" pages (BOFU)",
  "check": "Owned comparison/alternatives page exists for each top-3 named competitor (count, against frozen competitor set) AND each page has a structured comparison table + verdict capsule in first 30% (bool).",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (geo-content)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "AI engines heavily cite owned alternatives/vs pages for purchase-intent prompts; complements BOTH-10 (third-party) with the owned leg",
  "lever": "GEO"
 },
 "BOTH-NEW-01": {
  "id": "BOTH-NEW-01",
  "recommendation": "Google Business Profile entity signals",
  "check": "GBP claimed + verified (bool); NAP on GBP byte-matches homepage/schema canonical NAP (bool); primary category set + ≥1 post in trailing 30 days + avg rating ≥4.3 (numbers). Reproducible via GBP API. **High for local/multi-location brands.**",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization / r2 Reviews Monitoring",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "GBP feeds the Knowledge Graph + local AI answers directly; Google Business Profile docs 2026 [PRIMARY]",
  "lever": "BOTH"
 },
 "GEO-26": {
  "id": "GEO-26",
  "recommendation": "Mention share vs citation share (ghost-citation gap)",
  "check": "Over the **frozen captured response set**: mention_share = (#prompts where brand NAME in answer body)/N; ghost_citation_rate = (citations_to_brand_domain − named_mentions)/citations_to_brand_domain ×100. String-match counts on a frozen prompt+engine snapshot.",
  "impact": "high",
  "effort": "medium",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard (extend geo-monitor)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Semrush \"Ghost Citations Study\" 2026-06 (62% don't name brand) [VENDOR]",
  "lever": "GEO"
 },
 "BOTH-14": {
  "id": "BOTH-14",
  "recommendation": "Who-ranks-first (first-named / first-cited)",
  "check": "first_position_rate = (#prompts where client is first brand named OR first source cited)/N over the **frozen captured response set**; emit rank_first_competitor. Deterministic ordinal read of the frozen answer set.",
  "impact": "high",
  "effort": "medium",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard (extend geo-monitor)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Perplexity front-loading/visual-placement signal (PLATFORM-GUIDANCE row 12); AuthorityTech AI SoV 2026",
  "lever": "BOTH"
 },
 "GEO-27": {
  "id": "GEO-27",
  "recommendation": "Share-of-voice vs a fixed competitor set",
  "check": "share_of_voice_brand = (named mentions across N prompts × 5 engines)/(named mentions of ALL brands in the **locked 3-8 competitor set**) ×100, over the frozen captured response set. Sums to 100%.",
  "impact": "high",
  "effort": "medium",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard (extend geo-monitor)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "DigitalApplied \"AI Share of Voice\" 2026; trygeometrics SoV 2026",
  "lever": "GEO"
 },
 "GEO-28": {
  "id": "GEO-28",
  "recommendation": "GSC Generative AI report ingestion",
  "check": "ai_impressions_total + ai_impressions_by_url via GSC API; % change vs prior period (reproducible from Google). Boolean: ai_opt_out_enabled == false. **Rolling out broadly (no longer UK-restricted); impressions-only — no clicks / CTR / query data.** Blocked on GSC_SERVICE_ACCOUNT_KEY/GSC_SITE_URL.",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (seo-gsc edge function)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google \"Search Generative AI performance reports in Search Console\" 2026-06-03; broad rollout confirmed June 2026 [PRIMARY]",
  "lever": "GEO"
 },
 "GEO-29": {
  "id": "GEO-29",
  "recommendation": "AI referral tracking (GA4 AI Assistant channel + UTM)",
  "check": "ai_referral_sessions = sessions whose source matches `^.*(chatgpt\\.com|gemini\\.google\\.com|perplexity\\.ai|copilot\\.microsoft\\.com|claude\\.ai|openai\\.com).*`; reported as count + % of total. Caveat: ChatGPT mobile-app traffic passes no referrer → lands as Direct (known undercount).",
  "impact": "high",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (analytics ingestion) / i2 Performance Reporting",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "ChatGPT appends utm_source=chatgpt.com since June 2025; GA4 native \"AI Assistant\" channel May 2026 [PRIMARY-adjacent]",
  "lever": "GEO"
 },
 "BOTH-11": {
  "id": "BOTH-11",
  "recommendation": "Publish original first-hand experience + original data",
  "check": "Page has ≥1 first-person experience marker (\"we tested/measured/built\") AND ≥1 original data point not sourced from another site (pass/fail).",
  "impact": "high",
  "effort": "heavy",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google E-E-A-T Experience pillar; ConvertMate GEO Benchmark 2026 (original-data ~2.8× cited) [VENDOR-correlational]; Anthropic citations guidance [PRIMARY]",
  "lever": "BOTH"
 },
 "GEO-23": {
  "id": "GEO-23",
  "recommendation": "Brave Search indexation/ranking (Claude visibility)",
  "check": "`site:` query on Brave returns ≥1 indexed result (bool); brand/core-term query position in Brave **captured as a timestamped snapshot datapoint, not a hard pass/fail gate** (position is volatile).",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (add Brave rank-tracking leg)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Anthropic Brave subprocessor disclosure + Claude web-search docs; ~86.7% Brave-overlap 2026; PLATFORM-GUIDANCE rule 9",
  "lever": "GEO"
 },
 "GEO-24": {
  "id": "GEO-24",
  "recommendation": "IndexNow + Bing indexation (Copilot + ChatGPT-search reach)",
  "check": "`site:` Bing returns ≥1 result (bool); IndexNow key file at `/<key>.txt` returns 200 (bool); URLs submitted via IndexNow in last 30 days (count where instrumented). Google does not support IndexNow as of 2026-02.",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (a3 extension; IndexNow/Bing submission feature)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "dev.to \"Get Your Site on AI Search with IndexNow\" 2026; Bing Webmaster \"AI Performance\" preview 2026-02-09",
  "lever": "GEO"
 },
 "GEO-41": {
  "id": "GEO-41",
  "recommendation": "Gemini: Google AI Overviews / AI Mode optimization",
  "check": "Page indexed in Google (`site:` returns the URL, bool) AND GSC AI-features opt-out == OFF (bool, where GSC verified) AND recognized entities/1000w ≥15 (per the GEO-18 NER snapshot) AND ≥1 self-contained 40-60w answer capsule per target H2 (per GEO-02) AND query-fan-out sub-intent coverage ≥4/5 (per GEO-21). All deterministic counts/reads.",
  "impact": "critical",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 (query fan-out + RAG; AI Mode powered by Gemini 3.5 Flash, Google I/O 2026) [PRIMARY]",
  "lever": "GEO"
 },
 "BOTH-07": {
  "id": "BOTH-07",
  "recommendation": "Canonical tags correct/self-referential; single host",
  "check": "% of key URLs with valid rel=canonical resolving to a 200 indexable URL (target 100%); duplicate clusters (same title + near-identical content) >1 URL (target 0); single canonical host enforced via 301 (bool).",
  "impact": "high",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 (\"reduce duplicate content\") [PRIMARY]",
  "lever": "BOTH"
 },
 "BOTH-08": {
  "id": "BOTH-08",
  "recommendation": "JS content server-rendered / in crawlable HTML",
  "check": "Raw (non-JS) fetch of each key URL contains main body text + internal links (pass/fail); raw-HTML word-count ≥80% of rendered word-count (ratio).",
  "impact": "high",
  "effort": "heavy",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (diagnoses); **s6 Website Redesign — roadmap/unbuilt — implements**",
  "product_ref": {"id": "s6", "folder": "landing-page", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 (semantic HTML + JS SEO); findings §2",
  "lever": "BOTH"
 },
 "BOTH-09": {
  "id": "BOTH-09",
  "recommendation": "XML sitemap present, valid, referenced in robots.txt",
  "check": "Sitemap URL returns 200 + valid XML (bool); `Sitemap:` line in robots.txt (bool); sitemap URLs that are noindex/non-canonical == 0 (count, pass when 0).",
  "impact": "high",
  "effort": "quick",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google crawling best practices 2026-06-15 [PRIMARY]",
  "lever": "BOTH"
 },
 "BOTH-12": {
  "id": "BOTH-12",
  "recommendation": "Organization/Person schema w/ sameAs + stable @id; canonical NAP",
  "check": "Homepage/about has valid Organization JSON-LD with sameAs length ≥4 incl. Wikidata URL (pass/fail); distinct Organization @id across N≥5 templates == 1 (pass/fail); distinct normalized canonical brand-name strings across homepage title/schema/Wikidata/LinkedIn/GBP == 1 (pass/fail). **Scoped to entity/rich-result hygiene — NOT an AI ranking claim.**",
  "impact": "high",
  "effort": "medium",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google Organization structured-data docs 2026 [PRIMARY]; Momentic @id guide 2026; schema NOT an AI ranking lever (2026-06-15)",
  "lever": "BOTH"
 },
 "GEO-07": {
  "id": "GEO-07",
  "recommendation": "Wikidata entity with cross-source agreement",
  "check": "Wikidata QID resolves for the brand (exact-name SPARQL/lookup returns ≥1 item with P856 == client root domain) → pass/fail. **Entity-eligibility prerequisite (gates Knowledge Graph), not an asserted citation lever.**",
  "impact": "high",
  "effort": "medium",
  "delivery": "new-product",
  "product": "a11 Wikipedia Page Creation (extend to Wikidata; **catalog, not built**)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Profound 680M-citation study 2026 (Wikidata→Knowledge Graph); digitalapplied Entity SEO Guide 2026",
  "lever": "GEO"
 },
 "GEO-35": {
  "id": "GEO-35",
  "recommendation": "Entity presence as named brand-mention rate across 5 engines",
  "check": "Brand named in ≥X% of N fixed prompts across the 5 engines = brand-name occurrences/(N×5), over the **frozen captured response set** (reproducible for the same snapshot + date).",
  "impact": "high",
  "effort": "medium",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard (extend geo-monitor)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "findings §5 (Share-of-Model, 250-500 query set); Discovered Labs 2026 per-engine citation-rate gap [VENDOR-correlational]",
  "lever": "GEO"
 },
 "BOTH-18": {
  "id": "BOTH-18",
  "recommendation": "Score-reproducibility guardrail (frozen-input contract)",
  "check": "metric_run reproducible iff (prompt_set_hash, competitor_set_hash, engine_list_hash, response_set_hash, backlink_export_date, ner_model_id, gazetteer_hash, scoring_weights_version, classifier_model_id) unchanged; dashboard stores these hashes per run and asserts identical inputs → identical scores/shares. **Every drift-prone check above declares its frozen input as a required field — enforced, not aspirational.** Boolean: inputs_unchanged_since_last_run.",
  "impact": "high",
  "effort": "medium",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard + a3 scoring config (versioned)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Determinism requirement from task; repo \"dated snapshot\" caveat (findings §8)",
  "lever": "BOTH"
 },
 "GEO-31": {
  "id": "GEO-31",
  "recommendation": "LinkedIn presence (B2B/professional)",
  "check": "Brand AND ≥1 named expert each post substantive domain content on LinkedIn ≥4× in trailing 30 days (number, reproducible). **Brand-account leg = e10; named-expert thought-leadership leg = agent-direct/human, not the brand Agent.**",
  "impact": "medium",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "e10 LinkedIn Agent (brand) + agent-direct/human (named expert)",
  "product_ref": {"id": "e10", "folder": "linkedin-agent", "status": "live"},
  "source": "findings §2 (LinkedIn #1 for B2B/professional); Ahrefs 75k 2025-12-12 [VENDOR-correlational]",
  "lever": "GEO"
 },
 "GEO-32": {
  "id": "GEO-32",
  "recommendation": "Sentiment of brand mentions in AI answers",
  "check": "net_sentiment = (positive − negative)/total named mentions, range −1.0..+1.0, computed by a **deterministic lexicon classifier (e.g. VADER) with a frozen lexicon version** OR a pinned LLM whose labels are **cached/frozen per mention-snapshot** (re-runs read cached labels, never re-classify). Residual caveat: reproducible only against the frozen snapshot, not on fresh re-classification. Flag when <0.",
  "impact": "medium",
  "effort": "medium",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard (extend geo-monitor; feeds r2 Reviews Monitoring)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "findings §2 (reviews drive AI recs via sentiment); AuthorityTech AI SoV 2026",
  "lever": "GEO"
 },
 "GEO-34": {
  "id": "GEO-34",
  "recommendation": "Disambiguate entity from same-name collisions",
  "check": "Wikidata item has a non-empty description field AND schema/homepage includes ≥2 disambiguating attributes (location + foundingDate present) → pass/fail.",
  "impact": "medium",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google Knowledge Graph entity-linking; digitalapplied Entity SEO Guide 2026",
  "lever": "GEO"
 },
 "GEO-36": {
  "id": "GEO-36",
  "recommendation": "Per-engine expectation baselines",
  "check": "engine_index = client citation_share_engine / fixed_engine_baseline_share (stored constant, e.g. ChatGPT ~0.59%, Perplexity ~13.05%); index <1.0 flags under-performance. Baselines versioned, refreshed quarterly.",
  "impact": "medium",
  "effort": "quick",
  "delivery": "new-product",
  "product": "AI Share-of-Model Dashboard (extend geo-monitor)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "findings §1a-bis.9 (34,234-response study, ~46× gap; Discovered Labs 2026) [VENDOR-correlational]",
  "lever": "GEO"
 },
 "GEO-37": {
  "id": "GEO-37",
  "recommendation": "Keep canonical entity profile fresh (dateModified ≤90d)",
  "check": "dateModified on entity/about/pillar pages within 90 days of run date → pass/fail boolean.",
  "impact": "medium",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Task verified fact (content <3mo cited ~3×); Perplexity recency skew [VENDOR-correlational]",
  "lever": "GEO"
 },
 "BOTH-13": {
  "id": "BOTH-13",
  "recommendation": "Topical authority via consistent original publishing",
  "check": "Domain has ≥50 indexed original articles within one defined topic cluster AND publishing gap never exceeds 30 days over trailing 6 months (pass/fail).",
  "impact": "medium",
  "effort": "heavy",
  "delivery": "existing-product",
  "product": "e11 Newsletter Agent / blog-writer (orchestrated by a3)",
  "product_ref": {"id": "e14", "folder": "blog-agent", "status": "live"},
  "source": "Perplexity Publisher Program terms Jan 2026 [PRIMARY-adjacent] (≥50 indexed, consistent original publishing)",
  "lever": "BOTH"
 },
 "BOTH-16": {
  "id": "BOTH-16",
  "recommendation": "Readability + clean extractable structure (sized units)",
  "check": "Median section length 120-180 words AND no target section >300 words; **H2 ends in \"?\" OR matches a frozen intent-string list** (replaces subjective \"clear topic/question\"); ≥1 \"X is…\" definition for the primary entity ≤25 words at grade ≤12; Flesch reading ease ≥50 (pass/fail).",
  "impact": "medium",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "AI Overview extract analysis (134-167w favored; Machine Relations 2026); Princeton fluency lever KDD 2024 [CONTROLLED]",
  "lever": "BOTH"
 },
 "GEO-NEW-04": {
  "id": "GEO-NEW-04",
  "recommendation": "Conversational / long-tail intent capture",
  "check": "Share of target pages answering natural-language conversational queries (≥6-word question phrasing, matched against a **frozen conversational-query list**) ≥ threshold; answers self-contained for multi-turn follow-up (pass/fail per page).",
  "impact": "medium",
  "effort": "medium",
  "delivery": "existing-product",
  "product": "a3 SEO & GEO Optimization (geo-content)",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Voice + multi-turn assistant query capture; complements GEO-17/22 which assume the question set",
  "lever": "GEO"
 },
 "GEO-33": {
  "id": "GEO-33",
  "recommendation": "Vertical forums & Q&A (Quora / niche communities)",
  "check": "#Quora/vertical-forum threads ranking for the **frozen target query set** with a substantive disclosed brand-expert answer ≥3 (number); disclosure guard enforced.",
  "impact": "low",
  "effort": "medium",
  "delivery": "advisory",
  "product": "Reddit Presence Agent (extended to forums/Quora)",
  "product_ref": null,
  "source": "Discovered Labs per-engine bias 2026 (Perplexity community/forum ~46.7%) [VENDOR-correlational]",
  "lever": "GEO"
 },
 "GEO-38": {
  "id": "GEO-38",
  "recommendation": "No content fragmentation / micro-chunking (anti-pattern guard)",
  "check": "Body sections under 40 words == 0 on target pages (pass/fail); no page where >50% of sections are <40 words; thin-page count (indexable URLs <150 unique words) within cap; avg section length within 120-180w.",
  "impact": "low",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 (\"don't chunk content into tiny pieces\") [PRIMARY]; Princeton GEO KDD 2024",
  "lever": "GEO"
 },
 "GEO-39": {
  "id": "GEO-39",
  "recommendation": "Do NOT over-invest in schema as an AI lever (rich-result hygiene only)",
  "check": "Emitted JSON-LD validates with zero errors in Rich Results Test (bool) AND 0 schema types lacking an on-page visible equivalent (bool); FAQPage/HowTo not relied on for rich results (bool); policy gate: no new schema justified solely on an AI-ranking rationale (anti-pattern flag if violated). **Hygiene; weighted 0 in any ranking/citation score.**",
  "impact": "low",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Google generative-AI guide 2026-06-15 (\"no special schema.org markup needed\"); FAQ rich results dropped 2026-05-07; Ahrefs schema A/B test 2026 [VENDOR]",
  "lever": "GEO"
 },
 "GEO-40": {
  "id": "GEO-40",
  "recommendation": "llms.txt: optional, Lighthouse-clean, never a ranking lever",
  "check": "If present: `/llms.txt` returns 200 + passes the Lighthouse llms.txt audit (valid markdown links) (bool); if absent: audit == N/A, no penalty (bool); **weighted 0 in any ranking/citation score.**",
  "impact": "low",
  "effort": "quick",
  "delivery": "agent-direct",
  "product": "agent",
  "product_ref": {"id": "a3", "folder": "seo-geo", "status": "live"},
  "source": "Chrome Lighthouse llms.txt audit (June 2026); Google \"fine to use llms.txt, no Search ranking benefit\" June 2026 — hygiene only",
  "lever": "GEO"
 }
};
