// Verbatim port of the legacy karos-agents lab-spec config (RFC-04 "port the scoring config as-is").
// Source: karos-agents/products/onboarding/step-02-seo-geo/config/seo-geo-routing-config.json
// DO NOT hand-edit values here — this is a byte-for-fidelity transcription of the JSON asset.
export const routingConfigData = {
  "version": "a3-routing-v2",
  "scoring_weights_version": "a3-scoring-v2",
  "source_of_truth": "SEO-GEO-RECOMMENDATIONS-CATALOG.md (75 distinct rec_ids) + seo-geo-scoring-config.json (per-input measure/normalization/target/weight) + docs/a3-rec-catalog-v2.json (frozen rec->product/class lookup, committed, version-keyed)",
  "delivery_advisory_note": "2026-07-06 rec-catalog normalization (Albert): config/seo-geo-rec-catalog.json now carries a normalized product_ref {id, folder, status} per rec; legacy free-text product strings are kept verbatim for history and are never client-facing. Recs with product_ref null carry delivery 'advisory' in the rec catalog; at routing time 'advisory' is handled EXACTLY like this file's 'new-product' class (no runner, never auto-run, never silently dropped: flagged_gap + advisory surfacing), except client-facing copy presents the rec as advisory guidance, never as a Karos product offer. The routing[] rows, priority formula and determinism rules in this file are unchanged; product_ref feeds no scored metric and no inputs_digest. When docs/a3-rec-catalog-v2.json is committed (build item 7), it must be generated FROM the normalized catalog, product_ref included, version-keyed under scoring_weights_version.",
  "owning_function": "NEW supabase function a3-trigger-router, invoked inside recurring-agent-runner case 'monthly_geo'. The existing handleMonthlyGeo() Perplexity scan is unrelated and is NOT the owner.",
  "trigger": {
    "source": "input_values[] materialized by a3-trigger-router from frozen crawl_snapshot_hash per seo-geo-scoring-config.json (pure function, never re-measures)",
    "norm_materializer": "a3-trigger-router computes per-input norm 0..1 from snapshots; this function is net-new (no precomputed norm exists in repo) and is the implementation long pole",
    "fires_when": "per distinct rec_id, FIRE if min(norm across weighted input_weight>0 instances) < 1.0. Bands: norm>=1.0 pass (no action); 0.75<=norm<1.0 under_threshold/approaching (fires); norm<0.75 fail (fires). boolean/multi_bool: norm==1 pass else fail.",
    "exclusions": [
      "hygiene weight-0 inputs (GEO-39, GEO-40, BOTH-12) are report-only flags, never scored/paid calendar work (only trivially-safe pure-agent emits like GEO-40 llms.txt may schedule); excluded-from-calendar != excluded-from-manifest",
      "roll-up per rec_id = min norm across all its weighted instances; a rec fires once",
      "visibility-index OUTCOME metrics (GEO-11,GEO-12,GEO-26,GEO-27,GEO-35,GEO-14,GEO-32,GEO-36,BOTH-14) never fire a calendar task; their drivers fire instead",
      "GEO-36 is DIAGNOSTIC-ONLY, never fires a calendar task"
    ],
    "excluded_but_fired_surfacing": "every excluded-but-fired rec_id still writes a research_runs.payload.recommendations[] entry (live:false for gaps) AND a service_events 'diagnostic/report-only' row, so it is never a soft drop from the manifest or the decisions timeline (PORTAL-DASHBOARD-CONTRACT: every run/decision MUST insert a service_events row)",
    "score_lift": "(1 - norm) * input_weight  (defensible client-facing impact number)",
    "priority_formula": "priority_score = 100*IMPACT_W*EFFORT_W + 20*(1-worst_norm) + 10*(fire_state=='fail') + 5*deliverability_bonus - 3*evidence_penalty; IMPACT_W{critical:4,high:3,medium:2,low:1}; EFFORT_W{quick:3,medium:2,heavy:1}; deliverability_bonus{agent_asset:2,product_trigger:1,gap:0}; evidence_penalty{VENDOR-correlational:1,else:0}. Core term dominates (cell spine, 100..1200); additive terms bounded <100 (within-cell tiebreak only). Hard override: failing critical-eligibility recs (BOTH-01,BOTH-02,GEO-01,GEO-08,GEO-10) jump the queue. Final tiebreak: impact rank, effort, rec_id ascending."
  },
  "delivery_actions": {
    "agent-direct": {
      "count": 25,
      "execution": "a3-trigger-router calls execute-product-skill (skill_slug='karos-seo-audit'; literal step_id + step_guideline strings per rec, NOT enumerated handler names) -> EMITS asset -> client_deliverables row type='creative_batch' (assets in content_json) status pending review + approval_queue item",
      "auto_runnable": "yes (generate)",
      "auto_publish": "NEVER. seo-fix-agent applies ONLY when rec_actions.id status='approved' AND deliverable_id resolves to an approved client_deliverables row (else 403); commit-deliverable-to-git only after approval (and only with human approved_by when requires_risk_review); human Push-to-client to go live.",
      "approval": "approval_queue type='deliverable'; ceo-agent auto-approves SAFE types at >=90 ONLY when requires_risk_review=false; on-site-copy recs are tagged requires_risk_review=true at insert -> human-only"
    },
    "existing-product": {
      "execution": "trigger the mapped product runner by REAL catalog id via execute-product-skill / its own cron",
      "auto_runnable": "yes",
      "approval": "per that product's existing gate; measurement-only legs approval_required=false (dashboard KPI, not a calendar deliverable)",
      "note": "e6 Motion is `planned` -> its leg degrades to a gap until built. s6 Website-redesign is `ready` (a real product) -> BOTH-08 impl routes to a shipped runner, not roadmap. a11 Wikipedia is `planned` -> gap."
    },
    "new-product": {
      "execution": "NO runner. Write rec_actions row status='flagged_gap' + research_runs.payload.recommendations[] entry live:false + service_events 'recommended; build required' + team_todos human task + portal roadmap chip",
      "auto_runnable": "no",
      "approval": "n/a (nothing executes); human picks it up from team_todos / roadmap",
      "rule": "NEVER auto-run, NEVER silently dropped (HARD CONSTRAINT 3)"
    }
  },
  "routing": [
    {
      "rec_id": "SEO-02",
      "lever": "SEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_title_meta",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "quick"
    },
    {
      "rec_id": "SEO-06",
      "lever": "SEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_meta_description",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "quick"
    },
    {
      "rec_id": "SEO-07",
      "lever": "SEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "propose+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_slug_301",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium"
    },
    {
      "rec_id": "SEO-08",
      "lever": "SEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_alt_text",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": false,
      "client_visible": true,
      "cadence_hint": "quick"
    },
    {
      "rec_id": "BOTH-21",
      "lever": "BOTH",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_onpage_copy",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "quick"
    },
    {
      "rec_id": "BOTH-03",
      "lever": "BOTH",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_answer_capsule",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "heavy"
    },
    {
      "rec_id": "BOTH-04",
      "lever": "BOTH",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_onpage_copy",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium"
    },
    {
      "rec_id": "BOTH-11",
      "lever": "BOTH",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_qa_prose",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "heavy"
    },
    {
      "rec_id": "BOTH-12",
      "lever": "BOTH",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "validate+flag",
      "skill_slug": "karos-seo-audit",
      "step_id": "hygiene_flag",
      "auto_runnable": true,
      "approval_required": false,
      "requires_risk_review": false,
      "client_visible": "score-only",
      "cadence_hint": "hygiene-weight0-report-only"
    },
    {
      "rec_id": "BOTH-16",
      "lever": "BOTH",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_onpage_copy",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium"
    },
    {
      "rec_id": "GEO-01",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "propose+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_crawler_access",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": false,
      "client_visible": true,
      "cadence_hint": "quick-critical-eligibility"
    },
    {
      "rec_id": "GEO-02",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_onpage_copy",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium-critical"
    },
    {
      "rec_id": "GEO-03",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_onpage_copy",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium-critical"
    },
    {
      "rec_id": "GEO-08",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "propose+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_crawler_access",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": false,
      "client_visible": true,
      "cadence_hint": "quick-critical-eligibility"
    },
    {
      "rec_id": "GEO-09",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_evidence_block",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium-critical"
    },
    {
      "rec_id": "GEO-10",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "propose+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_crawler_access",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": false,
      "client_visible": true,
      "cadence_hint": "quick-critical-eligibility"
    },
    {
      "rec_id": "GEO-17",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_onpage_copy",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium"
    },
    {
      "rec_id": "GEO-18",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_entity_density",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium-anti-stuffing-gated"
    },
    {
      "rec_id": "GEO-22",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_jsonld",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": false,
      "client_visible": true,
      "cadence_hint": "quick"
    },
    {
      "rec_id": "GEO-34",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_onpage_copy",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium"
    },
    {
      "rec_id": "GEO-37",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_jsonld",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": false,
      "client_visible": true,
      "cadence_hint": "medium"
    },
    {
      "rec_id": "GEO-38",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_jsonld",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": false,
      "client_visible": true,
      "cadence_hint": "quick"
    },
    {
      "rec_id": "GEO-39",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "validate+flag",
      "skill_slug": "karos-seo-audit",
      "step_id": "hygiene_flag",
      "auto_runnable": true,
      "approval_required": false,
      "requires_risk_review": false,
      "client_visible": "score-only",
      "cadence_hint": "hygiene-weight0-report-only"
    },
    {
      "rec_id": "GEO-40",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_llms_txt",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": false,
      "client_visible": true,
      "cadence_hint": "hygiene-weight0-safe-auto-approve-whitelist"
    },
    {
      "rec_id": "GEO-41",
      "lever": "GEO",
      "delivery": "agent-direct",
      "product": "a3",
      "action_type": "generate+patch",
      "skill_slug": "karos-seo-audit",
      "step_id": "emit_onpage_copy",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "medium-critical-bundle"
    },
    {
      "rec_id": "SEO-01",
      "lever": "SEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "score",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "kpi"
    },
    {
      "rec_id": "SEO-03",
      "lever": "SEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "monitor",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "kpi"
    },
    {
      "rec_id": "SEO-04",
      "lever": "SEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit(lighthouse-audit)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "audit-report"
    },
    {
      "rec_id": "SEO-05",
      "lever": "SEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit(geo-technical)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "fixes->gate",
      "client_visible": true,
      "cadence_hint": "audit-report"
    },
    {
      "rec_id": "SEO-09",
      "lever": "SEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "monitor(backlink-analyzer+alert-manager)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "alert"
    },
    {
      "rec_id": "SEO-10",
      "lever": "SEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "monitor(backlink-analyzer+alert-manager)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "alert"
    },
    {
      "rec_id": "BOTH-01",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit->flag",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "read=no;fixes->gate",
      "client_visible": true,
      "cadence_hint": "critical-eligibility-audit"
    },
    {
      "rec_id": "BOTH-02",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit->flag",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "critical-eligibility-audit"
    },
    {
      "rec_id": "BOTH-05",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit->plan",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "fixes->gate",
      "client_visible": true,
      "cadence_hint": "audit-plan"
    },
    {
      "rec_id": "BOTH-06",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit->flag",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "fixes->gate",
      "client_visible": true,
      "cadence_hint": "audit-report"
    },
    {
      "rec_id": "BOTH-07",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit->flag",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "fixes->gate",
      "client_visible": true,
      "cadence_hint": "audit-report"
    },
    {
      "rec_id": "BOTH-09",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit->flag",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "fixes->gate",
      "client_visible": true,
      "cadence_hint": "audit-report"
    },
    {
      "rec_id": "BOTH-15",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit(backlink-analyzer)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "audit-report"
    },
    {
      "rec_id": "BOTH-17",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "join(rank-tracker+geo-monitor)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "report"
    },
    {
      "rec_id": "BOTH-19",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit(technical-seo-checker)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "audit-report"
    },
    {
      "rec_id": "BOTH-20",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit(technical-seo-checker)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "fixes->gate",
      "client_visible": true,
      "cadence_hint": "audit-report"
    },
    {
      "rec_id": "BOTH-NEW-01",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "a3+r2",
      "action_type": "audit+measure",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "GBP edits gated",
      "client_visible": true,
      "cadence_hint": "audit-measure"
    },
    {
      "rec_id": "GEO-21",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "audit(content-gap-analysis+geo-content)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "content->gate",
      "client_visible": true,
      "cadence_hint": "audit-brief"
    },
    {
      "rec_id": "GEO-23",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "track",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "datapoint"
    },
    {
      "rec_id": "GEO-24",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "submit+track",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": "submit->gate",
      "client_visible": true,
      "cadence_hint": "submit"
    },
    {
      "rec_id": "GEO-28",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "ingest(seo-gsc)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "kpi-blocked-on-gsc-secrets"
    },
    {
      "rec_id": "GEO-29",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "a3+i2",
      "action_type": "ingest",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "kpi-shared"
    },
    {
      "rec_id": "GEO-NEW-02",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "generate(geo-content)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "content"
    },
    {
      "rec_id": "GEO-NEW-04",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "a3",
      "action_type": "generate(geo-content)",
      "skill_slug": "karos-seo-audit",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": true,
      "client_visible": true,
      "cadence_hint": "content"
    },
    {
      "rec_id": "BOTH-13",
      "lever": "BOTH",
      "delivery": "existing-product",
      "product": "e11",
      "action_type": "trigger(newsletter-agent/blog-writer)",
      "auto_runnable": true,
      "approval_required": true,
      "requires_risk_review": "true-for-compliance-locked-clients(per-client regulatory lock in profile)",
      "client_visible": true,
      "cadence_hint": "content-net-new"
    },
    {
      "rec_id": "BOTH-08",
      "lever": "BOTH",
      "delivery": "existing-product+existing-product",
      "product": "a3 diagnose; s6 implement (s6 is `ready`, a real product)",
      "action_type": "diagnose->implement",
      "auto_runnable": "diag=yes;impl=yes(via s6)",
      "approval_required": "impl gated",
      "client_visible": true,
      "cadence_hint": "split-leg: a3 diagnose + s6 SSR impl"
    },
    {
      "rec_id": "GEO-13",
      "lever": "GEO",
      "delivery": "existing-product+new-product",
      "product": "i3 measure leg; Digital-PR/Earned-Mention earn leg(gap)",
      "action_type": "measure + earn",
      "auto_runnable": "measure=yes;earn=no",
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "split-leg: i3 KPI + earned-mention gap (two rec_actions rows)"
    },
    {
      "rec_id": "GEO-14",
      "lever": "GEO",
      "delivery": "existing-product+new-product",
      "product": "r2 measure leg(KPI,no calendar); Review-Acquisition build leg(gap roadmap chip)",
      "action_type": "measure + build",
      "auto_runnable": "measure=yes;build=no",
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "split-leg: r2 KPI + review-acquisition gap (two rec_actions rows; outcome leg never fires calendar)"
    },
    {
      "rec_id": "GEO-19",
      "lever": "GEO",
      "delivery": "existing-product+new-product",
      "product": "a3 audit leg; e6 Motion net-new(planned->gap) + YouTube GEO Agent(gap)",
      "action_type": "audit + trigger",
      "auto_runnable": "audit=yes;video=no(e6 planned->gap)",
      "approval_required": true,
      "client_visible": true,
      "cadence_hint": "split-leg: a3 audit + e6/YouTube net-new gap"
    },
    {
      "rec_id": "GEO-20",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "a3 cadence leg; e11 net-new content leg",
      "action_type": "schedule + trigger",
      "auto_runnable": true,
      "approval_required": "content->gate",
      "requires_risk_review": "true-for-compliance-locked-clients",
      "client_visible": true,
      "cadence_hint": "split-leg: a3 cadence + e11 net-new; noisy freshness metric, cooldown"
    },
    {
      "rec_id": "GEO-30",
      "lever": "GEO",
      "delivery": "existing-product",
      "product": "i2 measure + a1/a2 drive",
      "action_type": "measure+trigger",
      "auto_runnable": true,
      "approval_required": "drivers gated",
      "client_visible": true,
      "cadence_hint": "kpi+ads-driver"
    },
    {
      "rec_id": "GEO-31",
      "lever": "GEO",
      "delivery": "existing-product+agent-direct",
      "product": "e10 brand leg; agent-direct/human named-expert draft leg",
      "action_type": "trigger + draft(human-finished)",
      "auto_runnable": "brand=yes;expert=draft",
      "approval_required": true,
      "requires_risk_review": "true-for-compliance-locked-clients",
      "client_visible": true,
      "cadence_hint": "split-leg: e10 brand posts + agent-direct expert draft (two rec_actions rows)"
    },
    {
      "rec_id": "GEO-32",
      "lever": "GEO",
      "delivery": "existing-product+new-product",
      "product": "r2 sentiment-feed leg(KPI); AI Share-of-Model Dashboard compute leg(gap)",
      "action_type": "measure + compute",
      "auto_runnable": "feed=yes;compute=no",
      "approval_required": false,
      "client_visible": true,
      "cadence_hint": "split-leg: r2 feed + dashboard compute gap (two rec_actions rows; outcome leg never fires calendar)"
    },
    {
      "rec_id": "GEO-04",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "Digital-PR/Earned-Mention Agent",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "GEO-06",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "Digital-PR/Earned-Mention Agent",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "GEO-05",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "YouTube GEO Agent",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "GEO-16",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "Reddit Presence Agent",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "GEO-33",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "Reddit Presence Agent (forums/Quora)",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "BOTH-10",
      "lever": "BOTH",
      "delivery": "new-product",
      "product": "Comparison-Placement Program",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "GEO-07",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "a11 Wikipedia Page Creation (planned, not built)",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "GEO-15",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "a11 Wikipedia Page Creation (planned, not built)",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "GEO-25",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "a11 Wikipedia Page Creation (planned, not built)",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap (team_todos human task)"
    },
    {
      "rec_id": "GEO-11",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "AI Share-of-Model Dashboard (extend geo-monitor)",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap-visibility-index-component (live:false manifest entry, never fires calendar)"
    },
    {
      "rec_id": "GEO-12",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "AI Share-of-Model Dashboard (extend geo-monitor)",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap-score-spine (live:false manifest entry, never fires calendar)"
    },
    {
      "rec_id": "GEO-26",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "AI Share-of-Model Dashboard",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap-visibility-index-component (live:false manifest entry, never fires calendar)"
    },
    {
      "rec_id": "GEO-27",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "AI Share-of-Model Dashboard",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap-visibility-index-component (live:false manifest entry, never fires calendar)"
    },
    {
      "rec_id": "GEO-35",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "AI Share-of-Model Dashboard",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap-visibility-index-component (live:false manifest entry, never fires calendar)"
    },
    {
      "rec_id": "GEO-36",
      "lever": "GEO",
      "delivery": "new-product",
      "product": "AI Share-of-Model Dashboard",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap-diagnostic-only-never-fires-calendar (still writes live:false manifest entry; excluded-from-calendar != excluded-from-manifest)"
    },
    {
      "rec_id": "BOTH-14",
      "lever": "BOTH",
      "delivery": "new-product",
      "product": "AI Share-of-Model Dashboard",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap-visibility-index-component (live:false manifest entry, never fires calendar)"
    },
    {
      "rec_id": "BOTH-18",
      "lever": "BOTH",
      "delivery": "new-product",
      "product": "AI Share-of-Model Dashboard + scoring config (governance)",
      "action_type": "gap",
      "auto_runnable": false,
      "approval_required": "n/a",
      "client_visible": "roadmap",
      "cadence_hint": "gap-reproducibility-contract"
    }
  ],
  "routing_notes": {
    "coverage": "75/75 distinct catalog rec_ids routed (verified: catalog contains exactly 75). agent-direct=25 base recs; existing-product=31 distinct recs; new-product=18 distinct recs; 7 split-leg recs (GEO-13,GEO-14,GEO-19,GEO-20,GEO-31,GEO-32,BOTH-08) carry two delivery classes, appear once in the routing array with both legs described, and EACH leg gets its own rec_actions row so no gap leg is lost.",
    "agent_direct_count_resolution": "25, NOT 26 (the component divergence to 26 is wrong). GEO-NEW-01/GEO-NEW-03 do not exist in the catalog.",
    "agent_direct_allowlist": [
      "SEO-02",
      "SEO-06",
      "SEO-07",
      "SEO-08",
      "BOTH-03",
      "BOTH-04",
      "BOTH-11",
      "BOTH-12",
      "BOTH-16",
      "BOTH-21",
      "GEO-01",
      "GEO-02",
      "GEO-03",
      "GEO-08",
      "GEO-09",
      "GEO-10",
      "GEO-17",
      "GEO-18",
      "GEO-22",
      "GEO-34",
      "GEO-37",
      "GEO-38",
      "GEO-39",
      "GEO-40",
      "GEO-41"
    ],
    "geo31_expert_leg": "GEO-31 named-expert thought-leadership leg is agent-direct/human (draft, human-finished); brand-account leg is existing-product e10.",
    "auto_approve_whitelist": [
      "GEO-40 llms.txt",
      "SEO-06 meta description",
      "SEO-08 alt text",
      "GEO-22/37/38 JSON-LD that mirrors existing on-page facts"
    ],
    "risk_review_recs": "every agent-direct rec that rewrites visible body/title/answer copy carries requires_risk_review=true (SEO-02/07, BOTH-03/04/11/16/21, GEO-02/03/09/17/18/34/41, GEO-NEW-02/04); same flag propagates to e10/e11 legs (GEO-31,BOTH-13,GEO-20) for compliance-locked clients (any client flagged with a regulatory/compliance lock in its profile)."
  },
  "calendar": {
    "capacity_per_day": "1-2 deliverables/day default (configurable per engagement tier on service_briefs/client_products); weekly <=3-5; weekends skipped (BRT). ENFORCED as a publish ceiling: count check against rec_actions non-terminal statuses at insert AND before execute/publish; overflow stays status='recommended'.",
    "sequencing": "walk approved+schedulable queue in priority_score desc; failing critical-eligibility recs (BOTH-01,BOTH-02,GEO-01,GEO-08,GEO-10) first; effort lead-time: quick=this week, medium=1-2 wks, heavy/programs staged later (a heavy item consumes a week slot); dependents cannot precede their eligibility gate; overflow rolls to next month and is re-prioritized on re-score",
    "write_target": "each scheduled item -> client_deliverables row (type='creative_batch', assets in content_json; NO content_type column exists), delivered_at=scheduled_for (future delivered_at renders existing SCHEDULED badge, no new UI); assets in public client-content bucket (<slug>/seo-geo/<date>/file), strategy in private client-docs",
    "schedule_date_authority": "client_deliverables.delivered_at is the single source of the schedule date (referenced via rec_actions.deliverable_id). rec_actions.scheduled_for is a pre-deliverable staging value only, never a second source of truth.",
    "client_view_fields": [
      "deliverable_title (client-language, no rec_id/weights/costs)",
      "status_badge (SCHEDULED->delivered/published)",
      "scheduled_for date",
      "plain-english why (the rec)",
      "score trend from dashboard_snapshots (seo_score/geo_readiness/geo_visibility)",
      "service_events decisions timeline (incl. diagnostic/report-only rows for excluded-but-fired recs)",
      "roadmap chips for new-product gaps (never dated deliverables)"
    ],
    "rescore_cadence": "monthly_geo pg_cron (already ['a3']) -> a3-trigger-router = full re-score+re-route+re-prioritize+re-drip; weekly-crawl quick-win leg + quarterly deep-audit counter branch inside the SAME task body via new service_briefs fields last_weekly_run/quarter_counter; daily_delayed_report cron is the inter-month drip tick flipping scheduled->delivered on date. ZERO new cron jobs.",
    "dedupe": "key (client_id, rec_id, scope_hash) among non-terminal statuses; open match->suppress+bump recurrence_count; done+passing->no action; done+regressed->reopen via supersedes_id; done-within-cooldown(quick14/med30/heavy60d)->hold"
  },
  "infra_mapping": {
    "tables_reused": [
      "research_runs.payload.recommendations[]",
      "service_briefs",
      "service_events",
      "client_deliverables",
      "dashboard_snapshots",
      "approval_queue",
      "client_products",
      "clients",
      "team_todos"
    ],
    "functions_reused": [
      "recurring-agent-runner (NEW a3-trigger-router invoked inside case 'monthly_geo'; daily_delayed_report drip tick; 0 new cron jobs)",
      "execute-product-skill (skill_slug='karos-seo-audit'; literal step_id+step_guideline; pending_review)",
      "ceo-agent (SAFE={report,deliverable,social_post}@>=90 AND requires_risk_review=false; BLOCKED={proposal,action_plan,product_addition})",
      "seo-fix-agent (applies ONLY when rec_actions.status='approved' AND deliverable_id->approved client_deliverables; else 403; post-gate only)",
      "commit-deliverable-to-git (post-approval; clients/<slug>/seo-geo/; slug from DB; blocks auto-approved requires_risk_review items until human approved_by)",
      "portal-docs"
    ],
    "additive_schema": [
      "NEW TABLE rec_actions (single ledger; subsumes a3_gap_tasks/a3_action_items/seo_geo_action_queue). SCOPED to dedupe/recurrence/priority/slot accounting + FKs only. Columns: id, client_id, product_id default 'a3', run_id, rec_id, lever, delivery_class CHECK(agent-direct|existing-product|new-product), target_product, action_kind CHECK(agent_asset|product_trigger|gap), trigger_input, impact, effort, score_lift, worst_norm, priority_rank, fire_state, scope_hash, status CHECK(recommended|queued|scheduled|approved|applied|published|delivered|flagged_gap|resolved|superseded|deferred|dismissed), scheduled_for date (staging only), deliverable_id->client_deliverables.id, approval_id->approval_queue.id (approval lifecycle is READ from approval_queue, NOT mirrored), todo_id->team_todos.id (gap human task), supersedes_id, first_seen_run_id, last_seen_run_id, recurrence_count, scoring_weights_version, created_at, updated_at. RLS on; service-role write, anon SELECT; indexes (client_id,status),(client_id,scheduled_for),(rec_id),(run_id); dedupe partial-unique key (client_id,rec_id,scope_hash) among non-terminal statuses; rows never deleted (resolved/deferred). Does NOT copy recommendation text (in research_runs.payload), approval state (in approval_queue), schedule date (in client_deliverables.delivered_at), or human gap tasks (in team_todos). Portal NEVER reads this table. Sole writer: a3-trigger-router.",
      "NEW COLUMN approval_queue.requires_risk_review boolean default false (the existing requires_risk_review lives only on agent_skills and never reaches the approval row; ceo-agent.shouldAutoApprove must AND in !requires_risk_review)",
      "2 pure-JSONB fields on existing research_runs.payload.recommendations[]: rec_id, delivery_class (no DDL; 'live' boolean already exists)",
      "NEW FIELDS on existing service_briefs: last_weekly_run, quarter_counter, caps config (no new table)"
    ],
    "approval_gates": [
      "Gate 0 recommend-first: every fired rec -> rec_actions status='recommended' + research_runs.payload.recommendations[] entry (gaps live:false). Excluded-but-fired recs also get a service_events diagnostic/report-only row.",
      "Gate 1 delivery-class routing (silent-drop guard): agent-direct->pending-review deliverable+approval_queue; existing-product->queued+target_product; new-product->flagged_gap + team_todos human task (never dropped)",
      "Gate 2 ceo-agent scoring: auto-approve SAFE types @>=90 ONLY when requires_risk_review=false; action_plan (a3 impl plan / quarterly deep audit) and product_addition are BLOCKED -> always Albert",
      "Gate 3 safe-only auto-implement: ONLY whitelist emits (llms.txt, meta, alt, on-page-mirroring JSON-LD) auto-approve; any rewrite of visible body/title/answer copy forces requires_risk_review=true + human-only regardless of score; flag propagates to e10/e11 legs for compliance-locked clients (any client-specific protected-copy rule + any per-client newsletter-agent/blog compliance lock recorded in the profile)",
      "Gate 4 no client-site write without sign-off: seo-fix-agent requires rec_actions.status='approved' + approved deliverable (else 403); commit-deliverable-to-git blocks auto-approved requires_risk_review items until human approved_by; live application is a separate human Push-to-client action",
      "Gate 5 per-client caps ENFORCED: count check against rec_actions (non-terminal statuses, client window) at insert AND before execute/publish; overflow stays 'recommended' and drips later (prevents re-score-storm fan-out)"
    ]
  },
  "build_blockers_for_daniel": [
    "1. monthly_geo's handleMonthlyGeo() is a Perplexity scan and does NOT implement stages 1-7; spec/build a new function a3-trigger-router invoked inside case 'monthly_geo'.",
    "2. No weekly/quarterly task type; add last_weekly_run/quarter_counter to service_briefs and branch inside the monthly task body (no new cron).",
    "3. action_type values are not real handlers; each maps to a literal step_id + step_guideline passed to execute-product-skill with skill_slug='karos-seo-audit'.",
    "4. No content_type column on client_deliverables; use type='creative_batch' + content_json.",
    "5. s6 is `ready` (real product) -> BOTH-08 impl routes to it; e6 and a11 are `planned` -> gaps.",
    "6. No precomputed norm/input_values; a3-trigger-router must materialize input_values[] from crawl_snapshot_hash (the long pole).",
    "7. Commit docs/a3-rec-catalog-v2.json as the frozen, version-keyed rec->product/class lookup.",
    "8. rec_actions has no migration/writer; a3-trigger-router is the sole writer; add migration + approval_queue.requires_risk_review column.",
    "9. SAFETY (must precede any agent-direct execution): seo-fix-agent approval precondition; ceo-agent requires_risk_review check; auto-approve whitelist; enforced per-client caps; commit-deliverable-to-git human-approval guard.",
    "BLOCKED externally: GEO-28 GSC ingest pending GSC secrets."
  ],
  "determinism_guarantee": "Given identical inputs_digest (BOTH-18) and identical scoring_weights_version (freezing IMPACT_W, EFFORT_W, PASS=1.0/PARTIAL=0.75, rec_catalog map docs/a3-rec-catalog-v2.json, priority formula), the fired set, routing, priority order, and (modulo existing rec_actions state) the schedule are reproducible. Any weight/threshold change bumps scoring_weights_version and writes a drift_event."
}
;
