import { afterEach, beforeEach, describe, expect, it } from "vitest";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createKarosMediaTools, type ImageGenerationClient } from "../src/index.js";

/**
 * `media.generateImage` — the fallback for a visual need no library holds.
 *
 * prep run pubsub-21535110633863323 is why it exists: four providers, 36
 * candidates, and slide 5 still failed on "a timeline or roadmap with a
 * clearly labeled 'research' first phase, shot from above". No amount of
 * additional search backends produces that picture.
 */

const CTX = { runId: "run_1", clientSlug: "acme", productId: "instagram-agent", runKind: "recurring" } as never;

// A 1x1 PNG, base64 — enough to prove bytes reach disk.
const PNG_B64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg==";

let repoRoot: string;
beforeEach(async () => {
  repoRoot = await fs.mkdtemp(path.join(os.tmpdir(), "karos-gen-"));
});
afterEach(async () => {
  await fs.rm(repoRoot, { recursive: true, force: true });
});

function fakeClient(
  handler: (req: { model: string; prompt: string; config?: Record<string, unknown> }) => unknown,
): ImageGenerationClient {
  return { models: { generateImages: async (req) => handler(req) as never } };
}

const tool = (client: ImageGenerationClient | null, env: Record<string, string | undefined> = {}) =>
  createKarosMediaTools({ env, generationClient: client })["media.generateImage"]!;

describe("media.generateImage", () => {
  it("writes the generated bytes into the run's media cache and returns a repo-relative path", async () => {
    const client = fakeClient(() => ({
      generatedImages: [{ image: { imageBytes: PNG_B64, mimeType: "image/png" } }],
    }));

    const outcome = await tool(client).execute(
      { repoRoot, runId: "run_1", needs: [{ n: 5, prompt: "a quiet desk at dawn" }] },
      { ctx: CTX },
    );

    expect(outcome.status).toBe("success");
    const result = (outcome as { result: { candidates: Array<{ path: string; provider: string; licenseConfidence: string }> } })
      .result;
    expect(result.candidates).toHaveLength(1);
    expect(result.candidates[0]!.provider).toBe("imagen");
    // Owned outright — the one source with no third-party rights question.
    expect(result.candidates[0]!.licenseConfidence).toBe("generated");
    expect(result.candidates[0]!.path).toBe(".media-cache/run_1/n5-gen0.png");

    const written = await fs.readFile(path.join(repoRoot, result.candidates[0]!.path));
    expect(written.byteLength).toBeGreaterThan(0);
  });

  it("tells the vetting agent plainly that the image was generated, so it can clear rights honestly", async () => {
    const client = fakeClient(() => ({ generatedImages: [{ image: { imageBytes: PNG_B64 } }] }));

    const outcome = await tool(client).execute(
      { repoRoot, runId: "run_1", needs: [{ n: 1, prompt: "a timeline on a wall" }] },
      { ctx: CTX },
    );

    const description = (outcome as { result: { candidates: Array<{ description: string }> } }).result.candidates[0]!
      .description;
    // The gate cannot inspect pixels; it reads this. Without an explicit
    // provenance note it would default to sceptical, exactly as it should for
    // a web-sourced hit — and refuse an image we own.
    expect(description).toContain("AI-generated");
    expect(description).toContain("no third-party copyright");
    expect(description).toContain("a timeline on a wall");
  });

  it("passes the slide's brief verbatim, asks for the configured aspect ratio, and allows adults", async () => {
    let seen: { model: string; prompt: string; config?: Record<string, unknown> } | undefined;
    const client = fakeClient((req) => {
      seen = req;
      return { generatedImages: [{ image: { imageBytes: PNG_B64 } }] };
    });

    await tool(client).execute(
      { repoRoot, runId: "run_1", needs: [{ n: 2, prompt: "someone mid-explanation at a whiteboard" }], aspectRatio: "1:1" },
      { ctx: CTX },
    );

    expect(seen!.prompt).toBe("someone mid-explanation at a whiteboard");
    expect(seen!.config!["aspectRatio"]).toBe("1:1");
    // Slides routinely call for a person; without this Imagen refuses those
    // outright and the rescue fails on the needs it exists to cover.
    expect(seen!.config!["personGeneration"]).toBe("allow_adult");
  });

  it("honours IMAGEN_MODEL when set", async () => {
    let seen: { model: string } | undefined;
    const client = fakeClient((req) => {
      seen = req;
      return { generatedImages: [{ image: { imageBytes: PNG_B64 } }] };
    });

    await tool(client, { IMAGEN_MODEL: "imagen-9.9-test" }).execute(
      { repoRoot, runId: "run_1", needs: [{ n: 1, prompt: "x" }] },
      { ctx: CTX },
    );

    expect(seen!.model).toBe("imagen-9.9-test");
  });

  it("fills the needs it can when one of them fails, rather than abandoning all of them", async () => {
    const client = fakeClient((req) => {
      if (req.prompt === "bad") throw new Error("quota exhausted");
      return { generatedImages: [{ image: { imageBytes: PNG_B64 } }] };
    });

    const outcome = await tool(client).execute(
      { repoRoot, runId: "run_1", needs: [{ n: 1, prompt: "good" }, { n: 2, prompt: "bad" }] },
      { ctx: CTX },
    );

    // One gap filled beats neither, and the caller still learns why 2 missed.
    expect(outcome.status).toBe("success");
    const result = (outcome as { result: { candidates: unknown[]; unmet: Array<{ n: number; reason: string }> } }).result;
    expect(result.candidates).toHaveLength(1);
    expect(result.unmet).toEqual([{ n: 2, reason: "generation failed: quota exhausted" }]);
  });

  it("reports a safety refusal as content, naming the slide, not as a crash", async () => {
    const client = fakeClient(() => ({ generatedImages: [{ raiFilteredReason: "policy: people" }] }));

    const outcome = await tool(client).execute(
      { repoRoot, runId: "run_1", needs: [{ n: 3, prompt: "something disallowed" }] },
      { ctx: CTX },
    );

    expect(outcome.status).toBe("content_fail");
    expect((outcome as { reason: string }).reason).toContain("safety policy");
    expect((outcome as { reason: string }).reason).toContain("slide 3");
  });

  it("reports not_available with no backend configured, and never invents a client", async () => {
    const outcome = await tool(null).execute(
      { repoRoot, runId: "run_1", needs: [{ n: 1, prompt: "x" }] },
      { ctx: CTX },
    );

    expect(outcome.status).toBe("not_available");
    expect((outcome as { reason: string }).reason).toContain("GEMINI_VERTEX_PROJECT_ID");
  });

  // Two levels, not one: the `.media-cache/` prefix absorbs the first, so
  // `../escape` lands harmlessly at `<repoRoot>/escape`. It takes `../../` to
  // actually leave the bounds root.
  it("refuses a runId that would escape repoRoot", async () => {
    const client = fakeClient(() => ({ generatedImages: [{ image: { imageBytes: PNG_B64 } }] }));

    const outcome = await tool(client).execute(
      { repoRoot, runId: "../../escape", needs: [{ n: 1, prompt: "x" }] },
      { ctx: CTX },
    );

    expect(outcome.status).toBe("tooling_error");
    expect((outcome as { reason: string }).reason).toContain("escaped repoRoot");
  });

  it("is registered even when generation is unconfigured, so the workflow can check for the tool not the config", () => {
    expect(createKarosMediaTools({ env: {} })["media.generateImage"]).toBeDefined();
  });
});
