DEFECTS = [
 ("A-1/DS-16: renders paint engine or guessed faces (Space Grotesk, Inter, IBM Plex Mono, Georgia, Helvetica; DejaVu for mono) instead of the client's kit faces in 7 of 7 reviewed runs", "WS-02 (fonts) + portal P1 typography with provenance + data fix 1", "CDP painted-font guard after fonts.ready replaces fontFamiliesUsed; static scan forbids family literals in _design-system.css, the 8 plates, safety.ts and register stacks; Chromium sweep of 7 client kits incl. Hebrew Open Sans x 8 plates must fail on today's main; scripts/audit-brand-fonts.ts empty before promote"),
 ("C-5: numerals set in mono or body faces (500M+ in Hanken, IBM Plex Mono on 5 clients) and decorative 220px index numerals", "WS-02 / WS-06 (numerals #270)", "--f-figures + font-variant-numeric on every numeral host (.num-figure, .dv-figure, .dv-bar-value, .dv-tl-at, counters, recap figures); numeral-face probe asserts the painted family equals --f-num; decorative ordinals removed with a fixture"),
 ("DS-01: 7-14 distinct text sizes per carousel (up to 6 on one slide), 15-22px labels, a 220px numeral over an 84px headline, from a second scale, flavour multipliers, grow rungs and device px literals", "WS-06 (single role scale)", "composed-CSS lint: every font-size resolves to var(--t-head|--t-text|--t-source|--t-figure); single-source scale test; Chromium sweep 8 plates x en/he x each face asserts fontSizeSteps a subset of {H,T,S} (+F only on a lone figure); TYPE_STEP_CEILING armed at 3; fit ladder never grows and never crosses floors"),
 ("H-1/DS-05: text on photos at medium contrast (our cover 71/255 behind the headline vs a16z 7-34), light-tint scrims, framing triggered by a word count instead of a contrast failure", "WS-08 (full-bleed covers, merged 2026-09-25) + owner decision on #244", "hero legibility Chromium test clears 4.5:1 p10 behind every line on synthetic bright and dark grounds; the finding's remedy is framing, never shrinking; scrim anchor sequenced after both font-load passes; visual QA receives per-line hero contrast"),
 ("H-2: cover word overflow (XO 11+19 words, Pitch 28) and the poster copy block over 50% of the frame", "WS-08 / WS-10 (cover caps as parameters, WS-01)", "cover-cap unit tests refuse or cut XO's cover pre-render and pass Sitti's 8+12 with the deck cut to one sentence; render-time line-count check keeps the copy block <= 50%"),
 ("I-1: duplicate slides (Kindly 7/8 byte-identical), lost words and truncated text from render object keys overwritten per re-render and waive-then-merge", "WS-09 (set integrity, merged)", "render-carousel test: 8 then 7 slides for one postId land under disjoint renderKey prefixes; set-integrity refuses byte-identical and dHash<=6 pairs with text similarity >=0.6; text-coverage fixtures from the Kindly slide 5 and Sitti slide 4 documents fail; 09b throws on a second closer; storage lifecycle rule for superseded prefixes"),
 ("LANG-03: the copy prompts and value gates prescribe the 'X is not A. It is B.' shape and short fragments, force an ask and a question closer, reuse the rememberLine verbatim, and code rewrites copy after the gates pass (adds '…', orphaned pronouns, '( )')", "WS-10 (copy language, merged)", "readable-copy.test.ts with every shipped audit string as a failing fixture; prompt-text test forbids 'not this. that.' examples in angle, copy, revise and judge prompts; value-signals stops counting negation as tension; assembly tests forbid '( )', pronoun-opening remainders and '…'; loop test proves one revision request and re-lint before ship"),
 ("B-2: the site reader extracted fonts, palette and business facts from parked, for-sale, challenge and error pages (GoDaddy kindlyyours.com, Cloudflare on geektime, Shopify 402, Yotpo widget CSS)", "WS-03 (site identity guard, merged) + portal P2", "site-identity.test.ts on captured pages (GoDaddy -> parked, Shopify 402 -> unavailable, Cloudflare -> challenge, deel.com/the-pitch-by-deel -> ok); client-brief test leaves parked pages out of grounding and stops a run on an own-domain conflict; websiteStatus stored on save"),
 ("B-1/DS-08/D-1: the engine invents accent-gradient panels and picks devices from adjectives and a slug hash because no design-language document exists; brand.json is rewritten before dispatch", "WS-04 (design-language capture) + WS-07 (boxes from the language) + portal P3", "derive.test.ts on recorded captures (karoslabs radius 6 + #34343B hairlines, deel 200px pills + Bagoss, sitti Gaegu + coral pills, Cloudflare/GoDaddy pages derive nothing); byte-identity test for clients without a document; template scan forbids literal radius, gradient, shadow, border or font-family outside var(--dl-*|--f-*|--box-*); token-consumer contract; Karos fixture asserts hairlines and accent share <= 5%"),
 ("F-1/G-1/E-1: logo discovery runs even when a spec or upload exists, scraped substitutes ship (Deel's parent wordmark, the Geektime disc), the logo is sized by a 65px width clamp (Hanky Panky at 64x12), corners flip per run, backgrounds are placed unmeasured (XO white box, Sitti nested tile)", "WS-05 (logo spec; sizing merged, precedence and background open) + portal P4 + data fix 2", "fetch-spy workflow test proves zero homepage fetches when a spec exists and a failed download renders no logo plus a named finding; corner and box are a pure function of the spec across studio, eyebrow and badge states; the .brand-logo box never intersects the counter-pill rect (LTR and RTL fixtures); size test on real assets fails on today's 64x12; brand-logo-contrast reports a background for the XO PNG and returns only the inner mark for the Sitti tile"),
 ("IMG-03/M-1: AI pictures are a guarantee (MIN_GENERATED_IMAGES_PER_RUN 3), kit AI and imagery policies are ignored, generated frames rank above credited real photos, a diagram brief is rewritten into a photo", "WS-11 (graphics layer and imagery policy) + data fix 6 + owner decision vs RFC-24", "ai-imagery-policy.test.ts: a throwing fake image.generate is never called under 'never' (sitti, xodigital, thepitchbydeel) and the run still delivers >= 3 subjects; graphic-before-generation.test.ts (Sitti slide 4 chart with values equal to the copy, Karos slide 2 diagram) with zero generate calls; photoreal-record guard fixtures (Geektime auditorium, Karos Wrapped phone, XO Otto Lobo) refused before billing; golden-set eval pins the AI share <= the profile cap"),
 ("GFX-04/GFX-01: slides carry prose where a chart or diagram belongs, drawn numbers do not match the copy (Sitti weights 70% vs '500 points'), 'illustrative' device variants exist", "WS-11", "chart-numbers-verbatim.test.ts; render-time gate in 07 self-check fails a slide with unmatched numbers; icon-registry test (every IconName resolves, LICENSE present, no trademark); svg-safety test; Chromium calibration sweep of every graphic kind x slot x LTR/Hebrew with no overflow"),
 ("FMT-02/QUAL-01: no code check of resolution, watermarks, stickers, ad marks or third-party AI labels before a vision call; reels carry other shows' bugs (the Brex mark)", "WS-11 (pre-vet) with DT's gate values as a tuning table", "pre-vet step before 06-vet-images with fixtures for a watermarked frame, a 720p upscale, a dark first-2-seconds clip and an AI-labelled third-party image; failures logged in imageryMix, never repaired by generation"),
 ("DEF-01/J-1: competitor and own-post scoring reads hidden likes as 3, ranks posts under 72-96 h, uses a 12-post window that tracks age (r=0.83), includes pinned and promo posts, compares reels on likes and drops the shape fields", "WS-12 (benchmarks and priors) + karos-research social-history.ts and topic-engines.ts", "regression fixtures: a hidden-likes post never a number, a 30-minute-old post excluded or age-projected, a pinned post excluded, a reel scored on views only, mediaKind/slideCount/videoShare/coauthors/pinned/likesHidden kept; POSTS_PER_ACCOUNT 12 -> 36 (100 weekly); no score cap, no absolute fallback"),
 ("Q-1: the what-works learning doc has no producer in production, so preferredByPerformance and the format bandit fall back to rotation", "portal cron (#205-#207) beside reconcile/knowledge-sync + WS-12 consumers", "weekly job writes context/learning/instagram/what-works (LEARNING_DOC_NAMES) with AGE_CURVE, shrink_k 6, max_step 0.10, range 0.7-1.4, decay 0.85; consumer tests for 01b, 04h (rotation arm replaced once rows exist), 04i2, 03f; about $0.01 per client per week"),
 ("DS-13: eyebrows, series badges, the Pitch lockup, Sitti's arrow and DT's label slide sit inside the counter zone", "WS-08 / WS-09 (SAFE-ZONE gate) + WS-05 top-end inset", "SAFE-ZONE collision check in the render gate for the counter box, side crops and the bottom band with LTR and RTL fixtures"),
 ("DS-18: dead-space remedy rescales fonts per slide (the Karos 'Stratos stat' slide)", "WS-06 / WS-09", "DEAD-SPACE check with the sparse exemption; remedies are object, photo or layout, never fontScale; Karos stat-slide fixture"),
 ("R-1: parameters (word caps, sizes, floors, ratios, logo area, scrim band, mix bands, dedupe thresholds) live as scattered constants with no L1/L2/L3 resolution", "WS-01 (tuning.ts parameter registry; untouched as of 2026-09-25)", "tuning.test.ts: defaults equal today's constants; L3 overrides L2 overrides L1; unknown keys refused; every key has a unit and a doc line; run-budget posture cannot change mid-step"),
 ("LANG-11/LANG-09: closer templates carry follow and link-in-bio cards, prompts ask for a hashtag block, no bait or emoji validation", "WS-10 / WS-09 packaging validator", "packaging test: hashtags <= 5 from DNA.hashtagPool, bait-phrase regex per locale hard-fails, emoji <= DNA.emojiBudget, caption.firstLine <= 125 chars containing the subject entity, closer never a follow or link card"),
 ("S-1: no validator compiles each DNA against the L1 MUST gates, so v1 DNA values broke them (Karos cover H:T 2.95 and H:S 4.5, XO 3.1/4.4, Don Techno NAME:mono 4.7, Hanky Panky 30-34px support text, Geektime 259-302px and Hanky Panky 324px logos over the 240px cap, a ~28-word Karos photo cover)", "WS-01 (compileDNA) + CI", "render.py now checks every DNA's resolved block (ratios, neighbours, floors, cover and interior word caps, logo sizing rule and a scan for hand-set logo sizes) and fails the build; compileDNA gets the same checks as a CI test on every DNA before promote"),
 ("I-2: set integrity catches byte-identical and dHash<=6 pairs only, so slides that differ only in text on the same layout and object pass", "WS-09 (layoutRepeat gate)", "layout-repeat fixture: two consecutive slides with the same layout id and the same image hash, or the same graphic kind and data, fail; a DNA-declared typographic shape passes only when grounds alternate; exemption list read from the DNA"),
 ("LANG-14: no native proofing for he, pt-BR and fr copy (Hebrew agreement errors, English on XO slides)", "WS-10 (07h4 locale-proof)", "locale-proof fixtures per pack block on the final attempt; the Hebrew pack needs a named reviewer before it may refuse"),
 ("Data fixes (B-3/DS-17/LANG-15/IMG-06/O-2): wrong identity records at the source (Kindly Yours parked domain and gifting voice, Pitch retired kit and forbidden claims in projected context, XO stale brand.json, Karos label face and lockup, Sitti industry and logo, Geektime charcoal/Inter, N3 logotype SVGs not projected)", "audit.json data fixes 1-8 (prep then prod after promote) + portal P1-P4", "scripts/audit-brand-fonts.ts empty; scripts/report-brand-logos.ts and report-design-language.ts on the promote checklist; projection test proving typography, logo spec, imageryPolicy and designLanguage reach the engine for portal-onboarded and lab-owned clients; FONT_HOLD_ENABLED after data fix 1; the engine refuses a run whose DNA has no voice record"),
]

DECISIONS = [
 ("Logo corner: default to top-start (top-left LTR, top-right RTL) with top-end only by brand rule and dropped below the counter pill, or keep top-right as a general default?",
  "Top-start by default; top-end only when the brand's own lockup says so (The Pitch v4, Geektime's RTL tab) and then inset at least 112px below the pill; presence (every slide, cover and closer, none) stays a client value with a B2B TRY for Karos.",
  "scale.md ALL: logo_position shows no within-account signal (top-left 29+/36- p=0.46, none 56+/40- p=0.13); B2B is the only cut with a sign (none 8+/1- p=0.04, top-left 1+/7-); the engine's own measurement puts Instagram's n/N counter over the top-right corner (DS-13)."),
 ("Logo precedence: does an upload always beat the lab kit, even when the upload is a screenshot (karoslabs 2026-07-10, sitti app icon, xodigital images.jpg) and the lab holds the clean SVG?",
  "Needs your explicit sign-off, because it goes beyond point F as you stated it: 'the latest deliberate human choice wins, and a matching clean lab file is offered at staff approval'; for karoslabs, sitti and xodigital take the lab file now and mark it staff-approved, since each screenshot upload fails the background and tile checks.",
  "audit open question 2; WS-05 brand-logo-contrast fixtures (XO opaque PNG reports a background and never 'place'; Sitti nested tile returns only the inner mark); owner F ('an uploaded logo beats a scraped one') was about scraped substitutes, not curated kit files."),
 ("Label faces: Karos Labs Hanken uppercase (the live site), JetBrains Mono (the lab spec) or DM Mono (loaded but unused)? XO Digital the locked D5 kit (Fraunces/Geist/Geist Mono) or the live site's Plus Jakarta Sans + mono?",
  "Karos: DM Mono, the face the July grid's eyebrows and karoslabs.com actually use, with the lab spec updated to match. XO: the live feed's Plus Jakarta Sans ExtraBold/Regular plus one mono, because that is the measured house system the audience already sees and the serif cover underperformed.",
  "storm-lead L3-02 (tracked all-caps mono eyebrows in DM Mono); L3-05 (Plus Jakarta Sans two-tone headlines measured on the feed; the serif Buffett cover at 0.78x); data fix 1."),
 ("Commercial font licences: who supplies Relais/Fabriga (Hanky Panky) and GT Walsheim (Kindly Yours) files with a webfont licence covering rendered social images, and is Bagoss moot for The Pitch?",
  "Ask each client for files plus licence text now; until they land both clients are on FONT_HOLD (drafts render for review, nothing publishes) unless you sign off a named same-genre substitute per client, which then shows on the gate card of every post (never Georgia/Helvetica Neue, never silent); confirm the v4 Inter-only kit as canonical for The Pitch, which makes the Bagoss licence moot.",
  "A-2 (licence and glyph coverage gate); O-2 (v4 kit conflicts with the Bagoss/#201547 kit assumed by the a16z study); the 24 Sept Pitch run painted Bagoss 500 on #201547 with Deel's parent mark."),
 ("Covers: make the capped full-bleed poster with a measured, anchored shade the default and #244's framed card the fallback (WS-08, merged), reversing the trigger merged on your XO feedback?",
  "Needs your explicit confirmation before WS-08's behaviour is final, because it reverses #244, merged on your own XO feedback. Recommended: full-bleed photo cover with the text in one shaded band by default (at most 16 words, kicker included), framing only when the per-line contrast gate cannot pass; the XO case that prompted #244 is solved by the word cap (12 words) and the 60% navy scrim, not by framing.",
  "scale.md ALL: photo-dominant +0.21 99+/26- p<0.001, full-bleed photo + headline +0.06 79+/58-, text-only plate -0.09 15+/35-; a16z 7-34/255 behind text; H-1/H-2/DS-12; XO's own set is flat (5+/4-), so the XO DNA keeps the navy plate default and runs the photo cover as the X2/X-05 TRY."),
 ("Imagery: replace RFC-24's three-generated-frames guarantee with policy-gated generation behind code-built graphics and real pictures (WS-11), and set aiImagery 'never' for sitti, xodigital (except the capybara), thepitchbydeel, hankypanky, kindlyyours, dontechno and n3?",
  "Yes: MIN_GENERATED_IMAGES_PER_RUN 0, generation only in the declared classes (owned character, labelled concept), stock below the graphic rung and never for people; concept frames stay available where a brand allows them (karoslabs, geektime).",
  "IMG-03 (8 runs: 33 frames bought, 6 landed, 6 of 18 shipped pictures generated, ~$2.34 of $13.31); stock -0.11 11+/25- p=0.03; AI-looking +0.11 over 19 accounts p=0.48 (noise); 0 of the best posts in the startup and intimates sets use AI or stock; Aerie's #NotAI pledge 45,841 likes."),
 ("Stat figure: F = 1.5xH (about 170px against 220-246 today), used only as a slide's sole display element, or a larger tier?",
  "Lock F at 1.5xH as a lone display element within the 2.5:1 ratio to T, and re-run the Karos 'Stratos stat' slide locally before it ships; a number that is the story becomes the headline with its unit, as a16z sets it.",
  "C-1/DS-02; a16z uses no decorative index numerals and its 'Ages' headline is ~7% of height; our 220px numeral over an 84px headline produced ratios of 8.8-14.7:1; 4+ sizes -0.11 16+/43- p=0.0006."),
 ("Kindly Yours: confirm the canonical domain (thisiskindly.com's store is unavailable, kindlyyours.com is for sale), the category, and which wedding-favour runs to reject versus void.",
  "Set website to thisiskindly.com only if the client confirms it, else leave it empty; category intimates via import-lab-client --category; reject pubsub-21254987551616377 at its gate and void the two others with markers; delete the 14 gifting docs after a dry run; no run before profileSource 'lab' and the kit fonts land.",
  "B-3/LANG-15/DS-17 kindlyyours; storm-lead L3-04; WS-03 site-identity fixtures; the run sold wedding place cards with a 'complimentary discovery consultation'."),
 ("Hebrew copy pack: who reviews the readable-copy rules for Hebrew (where 'לא X אלא Y' is idiomatic) before the pack may refuse a Geektime draft?",
  "A native Hebrew editor (Geektime's desk or a named reviewer on Anna's side) signs the pack; until then the Hebrew pack flags but does not block, and the 'at most one לא X. per caption' rule stands as a soft limit.",
  "LANG-02/LANG-14 he pack; the reviewed run shipped five 'לא X.' fragments; audit open question 10."),
 ("Client classification boundary picks: Hanky Panky low or high involvement; Don Techno publisher or person; Sitti platform or publisher; Geektime audience mixed or B2C?",
  "Hanky Panky low with the AOV rationale logged and a re-check if the typical order crosses ~$100; Don Techno publisher (editorial voice, audio source from the account type); Sitti platform (two-sided marketplace) with publisher as the neighbouring row; Geektime mixed with a per-run high override for events campaigns.",
  "taxonomy judge client_mapping; robustness-v2: archetype and involvement largely one signal at 89 accounts (involvement adds +0.31% on top of archetype, p=0.21), so boundary picks shift only standards, not learned weights."),
 ("Benchmark scraping: approve the D45 carve-out from D43 (public posts, metadata and thumbnails only, aggregate use, 180-day retention, never shown as a client's numbers) so weekly peer reads and monthly benchmark scrapes can run automatically?",
  "Approve, with RFC-26's consent policy for competitors' public posts; without it the market study, the transfer table and the facet leaderboard cannot refresh and every L1 line stays frozen at the 2026-09-24 corpus.",
  "designs.json relevance/compounding/loops open questions; DT scraping cost ~$0.05-0.10 per post, ~$10 a month at 250 accounts; J-2 needs weekly 100-post reads."),
 ("Facet skill gate: accept +0.01 leave-one-account-out skill on two consecutive runs, >=20 accounts per group, survival of dropping any one source client and a carousels-only check before any facet (involvement, archetype) may carry engagement deltas, and keep category packs standards-only until they pass the same gate?",
  "Yes, but not permanently: involvement is closest today but fails the carousels-only slice, so every performance claim stays at L1 (global) and L3 (client) until a run passes; a pack stays standards-only (a line resting on under ~8 accounts is a convention or a TRY) until it passes the gate, and the monthly pooled pass (S-3) may propose pack TRYs meanwhile.",
  "robustness-v2: involvement +0.0096 p=0.01, archetype +0.0085, industry +0.0065 falling to +0.0016 without intimates; carousels-only (33 accounts) every card fails; design:impact jackknife."),
 ("Hanky Panky long caption (X8): run the 600-900 character story caption TRY although it conflicts with the house short caption (own maximum 148 characters)?",
  "Run it as the experiment it is (5 posts in the experiment slot, judged on saves per reach, giveaways excluded) and let the client's own grid decide; the kit's long-caption lift is giveaway-driven, so no default changes.",
  "LANG-12 hankypanky; intimates long caption 8+/0- confounded by contest rules (Aerie 9,855 comments); music long 6+/0-."),
 ("Don Techno asks (X12/X-16): allow a scene-culture question or a finite tally question in the caption despite the rule that DT captions carry no call to action?",
  "Keep the no-CTA rule as the default; allow X12 only on anniversary posts as a signed-off 5-post experiment measured on the comment index, and park X-16 (tally questions) until X12 reads, because DT's own data points slightly against forced asks.",
  "LANG-09/Q-4 dontechno; no CTA 14% vs 12%; the only two 6,000+ comment posts were a study and a policy; oeak's repeated ask decayed to 0.5-0.8x."),
 ("N°3 asks and facts: approve the quiet place question (X13) before its first post, and resolve the three open contradictions (street address, spa, services) so posts touching them can ship?",
  "Approve X13 as a caption-only French sentence about one apartment's real feature once measurement is live; get the client's written answer on address, spa and services before any maison-lane post that touches them; keep prices off every post.",
  "LANG-08/B-3 n3; legal.json claims_to_confirm; luxury comment prompt 0.167 over 3 accounts; the 'Une adresse, trois clés' signature rests on one address."),
 ("CTA style across the roster: remove link-in-bio and follow closers everywhere, keep one caption ask from the kit set or none, and make 'none' the default for publishers?",
  "Yes; house pointer lines (Geektime's article pointer, Sitti's 'map linked in bio', The Pitch's waitlist, XO's regulated closer) stay as fixed lines that do not count as the ask.",
  "scale.md ALL link-in-bio -0.13 26+/59- p<0.001; comment prompt +0.10 49+/25- but inflated 3x by the metric; a16z end cards 0/11 at 2x vs 12/28 without; startup link-in-bio 2+/7-."),
 ("Font substitutes: a kit-declared substitute no longer counts as the client's face; any client without its own licensed, decided face is on FONT_HOLD unless you sign off a named substitute for that client. Sign off which ones: Hanky Panky (Relais/Fabriga pending), Kindly Yours (Fraunces/Nunito for GT Walsheim), Don Techno (SF Mono in its renderer, swapped for JetBrains Mono), Karos Labs (label face undecided, Hanken caps meanwhile), XO Digital (D5 kit vs Plus Jakarta Sans)?",
  "Hold Hanky Panky and Kindly Yours until files and licences arrive (Kindly is blocked anyway); approve the JetBrains Mono swap for Don Techno; settle decision 3 for Karos and XO, whose candidates are all client-owned faces; every signed-off substitute shows on the gate card.",
  "A-1/A-2; auditors.json tally A-2 ('a substitute the kit states wins over genre matching'), which the alignment review found to be the loophole; Apple's SF Mono licence very likely excludes rendered social images."),
 ("Logo sizes: every DNA loses its hand-set logo size for the equal-area rule (Geektime's wordmark from 24-28% of width to at most 240px, Hanky Panky's from ~30%, Don Techno's monogram from a 160px box to ~70px, Karos, Pitch, Kindly, Sitti, XO and N3 likewise); XO drops its second footer mark and Sitti moves to one bottom-right position. Accept, or record per-client size exceptions in the BrandLogoSpec?",
  "Accept the rule and record any exception you want in the spec (not the DNA), with the render compared side by side first; the rule is what makes 'one optimal size chosen by a rule' true.",
  "E-1; v1 DNAs hand-set sizes that broke the 240px cap (Geektime 259-302px, Hanky Panky 324px); logo_position no L1 signal."),
 ("Icons: you asked to add icons and graphics, but icons measure -0.09 over 69 accounts (18+/38-, unlabelled decorative use). The guidelines now make labelled, code-built icons and graphics a default capability with a band per kit (marketing 1-3 per 8 slides, fintech 2-4, tech news 0-2, startups 0-2 inside pills, intimates 0-1 on cards, travel the product pin, music and luxury 0). Confirm the bands?",
  "Confirm, with the band counted in set integrity and the icons judged on saves and sends per reach through the loop; N3 stays at 0 by your 2026-09-08 rule and Don Techno at 0 because nothing may cover the footage.",
  "owner M; GFX-01/GFX-03; scale.md icons -0.09 18+/38-; data graphics lift 3 (fintech), icons-with-data 2.67; B2B icons 1+/6- (n=7)."),
 ("Word caps: lower the per-slide hard cap from 50 to 35 words and cap a full-bleed photo cover at 16 words in all (20 on a plate or card cover), which moves Geektime's news lane from 30-50 to 25-35 and XO's interiors from ~30 to 25 plus a graphic?",
  "Yes; a code-built graphic replaces prose first, and the rest folds into the caption one line per slide.",
  "owner M ('too text-heavy') and H ('less text'); M-2/H-2; a16z explainers of 25-54 words went 0/5 at 2x; our runs 39-44 words a slide."),
 ("Complete sentences: LANG-01 is now a MUST for every statement, with only labels exempt (names, eyebrows and series labels, kickers, credits and sources, badges, pills, chart and icon labels, step indices, a fixed house pointer line, hashtags). Confirm the label list, which removes Sitti's fragment-lint exemption and luxury's 'often no sentence' wording?",
  "Confirm; Sitti keeps its lowercase, no-period casing because casing comes from the DNA, and a DNA may not widen the label list.",
  "owner C ('complete human sentences'); LANG-01; scale.md fragments -0.07 48+/83- p=0.003."),
 ("Experiment throughput: raise the experiment share from 1 in 10 to 1 in 5 while a client's transfer queue holds more than 8 items, require at least 5 posts per arm, and hold queues for clients that cannot measure (N3 until a scraper key, Kindly while blocked)?",
  "Yes; at 1 in 10 and 3 posts a week Karos's ~20-item queue takes over a year and 2-3-post reads are noise. Small accounts (Karos, XO, Sitti) read on saves and sends per reach and non-follower reach, and new reel formats run first as Trial Reels.",
  "P-1/P-2/REEL-02; auditors.json transfers (every client gets 2-6)."),
 ("The Pitch and a16z: confirm you meant a16z's discipline (two sizes plus meta, short covers with a proper noun, 0-12-word story slides, darkened real photos, ending on the idea), not its look, since the v4 kit fixes the look?",
  "Confirm discipline, not look; the a16z families (archival 'then', manifesto, subtitled stills) stay TRYs on the v4 kit.",
  "O-1/O-2; ig-dna-thepitchbydeel lines 1 and 12."),
 ("Spend: the analysis kept the run budget untouched (your '$5 is fine' was about scraping); confirm that the guidelines' cost rule stays 'code before model calls, graphics before generation' with no new holds.",
  "Confirm; the only cost items these guidelines add are the weekly own-grid read (~$0.01 per client), the weekly market scan (~$0.07, incremental: new posts only plus refreshed metrics on posts under 30 days; a full 100-post re-read of 6-9 peers would cost $30-90 per client per week) and one haiku-class classification call at onboarding.",
  "R-1; dt.json cost lines; memory instagram-feedback-round-2026-09-24 (no run-budget change, no new holds)."),
]

SUMMARY = ("Compiled 108 audited rows and 32 transfers into a three-layer Instagram guideline set organised by the judged taxonomy: L1 platform ({n_l1} lines: MUST gates, DEFAULT mechanisms, TRY experiments, and the null results recorded as noise) with a {n_params}-key parameter block; a thin middle of standards-only cards (archetype x7, involvement x3 with the B2B/B2C audience modifier, locale as a qualifier) plus eight category packs (marketing-advertising, tech-business-news, startups-venture, fashion-intimates, travel-local-discovery, personal-finance-investing, music-nightlife, luxury-hospitality-real-estate) each within 25 lines; and nine client DNAs within 15 lines each carrying the classification record, the resolved parameter values, the client's own standards and the transfers as TRY lines with their twist. Rows refuted by both skeptics were dropped (X1 photo-dominant to intimates, whose substance survives in L1 IMG-01/H-3 and the Hanky Panky DNA); rows refuted once were narrowed (D-2/DS-09/GFX-02 'no device by default' to TRY at L1 and DEFAULT in startups and fintech; SCR-01 to TRY at L1 and DEFAULT in tech news; TOP-05 credit DEFAULT with the Collab invite TRY; X3, X-03, X-17 to the narrower experiments named). Owner standards and defects keep the scope he stated: fonts, two sizes plus meta, complete sentences, boxes in the client's language, the logo rule, uploaded-beats-scraped, background removal, shaded photo covers and set integrity (no two slides alike) are MUST at L1 with {n_defects} defects mapped to WS-01..13 and their guards. Version 1.1 applies the alignment review: every DNA is validated against the L1 size ratios, floors, cover and word caps and the logo rule (DNAs choose only logo variant, position, treatment and presence); a kit-declared font substitute is a FONT_HOLD unless the owner signs it off and is shown on the gate card; code-built icons and graphics are a default capability with per-kit bands; complete sentences are a MUST with a label list; small-n pack lines are conventions or TRYs; Reels craft, a trend-watch, a pooled scale pass and faster experiments are added at L1. Performance claims live only at L1 (global, one vote per account) and L3; category packs and facet cards hold standards and parameter values, with the industry statistics carried as evidence refs, because the grouping test found involvement, archetype and audience ahead of industry and every card failing on carousels alone. {n_decisions} decisions are listed for the owner with data-backed recommendations, the largest being the logo corner, logo precedence, label faces, font licences, capped full-bleed covers over #244, the end of the three-generated-frames guarantee, the D45 scraping carve-out and the facet skill gate.")

README_INTRO = """# Instagram layer guidelines (v1.1, 2026-09-25, alignment fixes applied)

Compiled from the 2026-09-24 owner feedback round (points A-S), the 108 audited rows in `auditors.json`, the 32 transfer candidates, the 183-account within-account study (`scale.md`), the a16z deep dive, the Don Techno audit and the judged layer-system and taxonomy designs.

## The stack

- **L1 platform** (`L1-platform.md`): Instagram craft, code gates and every pooled performance default, learned across all benchmark accounts with one vote per account. The only layer besides L3 that may say "X lifts engagement". Albert approves every L1 line and every MUST.
- **L2 facet cards** (standards only, never an engagement claim, each key with exactly one owner):
  - `facet-archetype.md` (closed list of 7: brand, place, person, publisher, platform, business, institution)
  - `facet-involvement.md` (none, low, high) plus the audience modifier (B2B, B2C, mixed) on two keys
  - `facet-locale.md` (en, he, pt-BR, fr, es, multi): a qualifier on any line, not a layer
- **L2 category packs** (`ig-kit-<category>.md`, one per field served, at most 25 lines): compliance and claims values per jurisdiction, entry points, calendar, proof conventions, lingo, imagery source, visual conventions, peer set and baselines, and the parameter values the renderer and copy steps read. Industry statistics appear only as evidence refs; a performance-derived line is written as a convention or parameter value, or as a TRY, and a statistic from fewer than ~8 accounts is TRY-level evidence that never carries a DEFAULT by itself.
- **L3 client DNA** (`ig-dna-<slug>.md`, one per client, at most 15 lines): the classification record, the brand-kit values, overrides with a reason, kit lines the client skips, the client's own standards, learned weights (shrunk toward L1, never toward a facet) and the transfers as TRY lines with their twist.

Precedence at run time: L1 hard gates > run input (post job, product line) > L3 DNA > facet cards and category pack (a plain union, keys never overlap) > L1 defaults. Between two conflicting prose lines the narrower wins. No line overrides a gate or the brand kit. `compileDNA(client, run)` is pure, runs at dispatch with no model call, and records which layer and document version produced every key.

## Validation

`render.py` fails the build when a kit exceeds 25 lines, a DNA exceeds 15, a line lacks strength, dimension or evidence, or a DNA's resolved block (`_src/resolved.py`) breaks an L1 MUST: H:T <=2.5, H:S <=4, neighbours >=1.35x, T >=36px, S >=26px (30 unless tracked caps), cover H >=96px (64 on a declared photo-hook cover), cover words <=16 on a full-bleed photo and <=20 otherwise, interior words <=35, a logo sized only by the equal-area rule, and no hand-set logo size left in a DNA's text.

## Line format

`N. [STRENGTH][dimension] one sentence (evidence: row ids, statistics, sources)`. STRENGTH is MUST (a gate enforces it), DEFAULT (applies unless overridden) or TRY (an experiment slot, measured); n/a marks a recorded null result. Dimensions: format, cadence, strategy, process, imagery, graphics, font sizes, design, layout, logo, language, hook, other. Statistics read "mean within-account difference over n accounts (positive+/negative-, sign-test p)" from `scale.md`, one vote per account.

## Client mapping (archetype | category pack | involvement | audience | locale)

| client | archetype | pack | involvement | audience | locale |
|---|---|---|---|---|---|
| karoslabs | business | marketing-advertising | high | B2B | en |
| geektime | publisher | tech-business-news | none | mixed | he |
| thepitchbydeel | institution | startups-venture | high | mixed | en |
| hankypanky | brand | fashion-intimates | low (borderline) | B2C | en |
| kindlyyours | brand | fashion-intimates | low | B2C | en |
| sitti | platform | travel-local-discovery | low | mixed | en |
| xodigital | platform | personal-finance-investing | high (regulated) | B2C | pt-BR (BR) |
| dontechno | publisher | music-nightlife | none | B2C | en |
| n3 | place | luxury-hospitality-real-estate | high | B2C | fr (FR) |

## Key ownership (one owner per parameter key)

- L1: canvas, safe zones, text sizes per slide and ratios, size floors, line measure, cover caps, word lanes, slide band limits, layout-repeat rule, scrim, contrast, logo area (always the equal-area rule) and position rule, design-language keys, reels craft, market-read cadence, performance-surprise threshold, imagery ladder, AI policy classes, screenshot cap, third-party share, caption first line and hashtag clamp, dedupe mechanics, loop thresholds, freshness, timeliness classes, dead space.
- Archetype: voice_person, face_on_camera, produced_vs_ugc_look, audio_source (hard), cadence_default, collab_style, news_peg_handling, series_affinity.
- Involvement (+ audience modifier): default_post_job_mix, brand_vs_activation_ratio, cta_intensity, register_intensity, format_lead, proof_person_style.
- Category pack: compliance values, entry points, calendar, proof conventions, lingo, imagery source and photoShareMin, graphics mix, icon band and device vocabulary, slide band, cover and interior word caps within the L1 lanes, captionChars, askSet and askPolicy, hashtag count, register value, questionForm, headlineTier, peer set and baselines.
- Locale: script direction, register pack, number/date/currency format, proofing, jurisdiction key.
- Client DNA: brand kit (faces, palette, logo variant, position, treatment and presence but never its size, design-language tokens incl. table style and icon band within the kit's), classification record, overrides with reasons, forbidden claims and compliance lines, hashtag pool, emoji budget, postsPerWeek, timezone, dedupe windows, learned weights, experiment queue.

## Rows dropped or narrowed by the skeptic tally

- Dropped (refuted twice): X1 (photo-dominant, saturated colour to intimates). Its substance already lives in L1 IMG-01/H-3/DS-06 and the Hanky Panky DNA's photo-first system; Kindly Yours is excluded until its record is fixed.
- Narrowed (refuted once): D-2, DS-09 and GFX-02 merged into L1 DS-09 ('a device must encode a fact' stays a standard; 'no device by default' TRY at L1, DEFAULT in the startups and fintech packs, excluded for intimates); SCR-01 TRY at L1, DEFAULT receipt slide in tech news and fintech, Geektime's template an L3 exemption; TOP-05 credit and source-first DEFAULT, Collab invite TRY, never private customers or N3 guests; X3 a low-priority Karos text-carousel experiment governed by the two-sizes rule; X-03 a study series with the number inside a sentence and code-built charts, only after the scoring fixes; X-17 the saison lane fed by an official-source list as one French sentence, no countdown or first-mover target.
- Killed at the storm stage and not carried: storm-lead L1-03 (register gate), L1-07 (huge headlines), L1-10 (corner logo marks weak posts), L1-19 (bold accent beats muted), L1-20 (typeface register), and the cross-account 'reels 10x' finding.

## Documents
"""
